### ISSUE TITLE
migrate to codecov

### ISSUE THREAD

**Issue by zbeekman** [jacobwilliams/json-fortran#106]
Recently coveralls has been really unresponsive, and the dependency on cpp-coveralls makes me think that using coveralls is not as robust as it could be. It looks like codecov has good out of the box support for C/C++ and that nothing will need to be done to support Fortran, although I haven’t tried it. They also have a slick browser plugin that shows coverage info right in github. If @jacobwilliams is open to switching, I may take a crack at migrating to codecov. It looks like it will consist of changing one line and deleting one or two others in .travis.yml and switching the badge in the README.md

**Comment by zbeekman** [comment]
If you install the [codecov browser extension](https://github.com/codecov/browser-extension) you can then go check out [my branch](https://github.com/zbeekman/json-fortran/blob/codecov/src/json_module.F90) where I've [updated the .travis.yml](https://github.com/zbeekman/json-fortran/commit/e22ed302294cdca7b4e1e3cc2e52166313ef3627).

Here are some screen shots

Look at lower right hand side to see coverage embedded in GH webpage next to commit hash
![screen shot 2015-06-08 at 4 55 09 pm](https://cloud.githubusercontent.com/assets/279612/8045152/7d266c56-0dff-11e5-9048-1550116d1aac.png)

Toggle-able coverage info when browsing source code on GH:
![screen shot 2015-06-08 at 4 55 57 pm](https://cloud.githubusercontent.com/assets/279612/8045204/bf37e638-0dff-11e5-9115-6160988c6970.png)

Highlighting in GH showing coverage:
![screen shot 2015-06-08 at 4 57 01 pm](https://cloud.githubusercontent.com/assets/279612/8045211/c99b13ac-0dff-11e5-8ae6-00f2ad2b94db.png)

**Comment by jacobwilliams** [comment]
Lemme take a look. If it's easier for a poor Fortran man, then I'm OK with it.

**Comment by zbeekman** [comment]
IMO, it is much easier… but it’s totally your call since coveralls does work

**Comment by jacobwilliams** [comment]
I like it. The browser plugin is great!

**Comment by zbeekman** [comment]
Much nicer IMO. There are some settings per repo that you can tweak too, like PR comments and coverage thresholds.

**Comment by zbeekman** [comment]
Also coverage graphs over commits that can be embedded in markdown.

**Comment by szaghi** [comment]
Hi all,

@zbeekman: as always I like your suggestions and I am greatly inspired from you. As the coverage is concerning, I agree that cpp-coverall dependency is not a robust solution. I will try codecov.io very soon. 

Thank you very much for sharing your idea!

Stefano

**Comment by zbeekman** [comment]
@jacobwilliams if you haven't done so already, check out the settings at https://codecov.io/github/jacobwilliams/json-fortran?ref=master under the "features" menu/link on the right. Specifically the "Pull Request Comment" and "Github Status" menu items hold some settings that can be adjusted to your liking.
