### ISSUE TITLE
Problems Reading DE405

### ISSUE THREAD

**Issue by OrbitalMechanic** [jacobwilliams/json-fortran#108]
The ephemeris_test step is showing problems reading DE405. At this point the is obtaining the ephemeris span from the header. Subroutine ephemeris_test is reporting

Ephemeris initialized
JD range:  *************** to           -0.000

 error: jed out of bounds.
 jed   =    2451536.5000000000     
 ss(1) =   -1.3078965099637064E+299
 ss(2) =   -7.1054099667486029E-015 

When it should be reporting the range 

2305424.5 to 2525008.5

Please advise.

P.S. - to build DE405, I'm using the version of asc2eph.f at ftp://ssd.jpl.nasa.gov/pub/eph/planets/fortran/

**Comment by jacobwilliams** [comment]
I think this is for: https://github.com/jacobwilliams/Fortran-Astrodynamics-Toolkit/issues  ?

**Comment by jacobwilliams** [comment]
I updated the [readme](https://github.com/jacobwilliams/Fortran-Astrodynamics-Toolkit/blob/master/README.md) to indicate the procedure for compiling the ephemeris file. It works for me, I get:
```
Ephemeris initialized
JD range:      2305424.500 to      2525008.500
```
If you are still having problems, please post an issue on the F.A.T. page.
