### ISSUE TITLE
automatic connect in figure

### ISSUE THREAD

**Issue by nemati456** [jacobwilliams/json-fortran#113]
hi!
I have a problem with tecplot
I want to plot 2 separate circule in one figure but.......
tecplot connect last node of first to first node of second circle automatically.
Its make problem for my other work
in the second figure this connect is between airfoil and circle
this is the code(or attached file)
with regad!

implicit none
integer::i,j
real::r1,teta,r2,r
real,dimension(0:361,2):: x, y
r1=2
r2=5

do j=1,2
teta=0
if(j==1)then
r=r1
j=1
else
r=r2
end if
do i=0,360
x(i,j)=r*cos(teta)
y(i,j)=r*sin(teta)
teta=3.1415/180+teta
!print*,i,teta,x(i,j)
end do
end do

OPEN(UNIT=10,FILE='RESULT circle.PLT')
WRITE(10,*)'VARIABLES="X","Y"' 
WRITE(10,*)'ZONE I=',361*2,'F=POINT'
do j=1,2

do i=0,360

WRITE(10,*)x(i,j),y(i,j)
END DO 
enddo

close(10)

end
![eliptic](https://cloud.githubusercontent.com/assets/12984799/8294963/8a777b46-1955-11e5-8caa-2d0d9fe25b3a.jpg)
![export](https://cloud.githubusercontent.com/assets/12984799/8294964/8aaebd9a-1955-11e5-9a27-4dd5ce262e35.jpg)

**Comment by jacobwilliams** [comment]
spambot maybe?

**Comment by nemati456** [comment]
no i human :D 
 i have problem with this question and refrence about this problem is very poor
 would you pls answer my question 
thanks a lot

**Comment by zbeekman** [comment]
This is not the correct forum to be asking questions about Tecplot. There is a Tecplot user forum. Please ask your question there. This software has nothing to do with Tecplot.
