### ISSUE TITLE
finer control of real format printing

### ISSUE THREAD

**Issue by zbeekman** [jacobwilliams/json-fortran#117]
I’m toying with the idea of adding some options to json_initialize to control sign printing (suppress always or force always, e.g., 99 vs  +99, right now this behavior is ‘processor dependant’) and also to select which output edit descriptor governs reals:
 * `e`—current output exponential format
 * `g`—general output edit descriptor, sloppy but more natural, behaves like `f` edit descriptor or `e` edit descriptor depending on size of exponent
 * `es`—scientific edit descriptor
 * `en`—engineering edit descriptor

The logic to compact reals should be compatible with all of these and `g` edit descriptor will help test writing exponent-less floats, which is currently the largest single chunk of untested code. (It’s effectively dead code because numbers with exponents are the only ones ever passed.)

**Comment by jacobwilliams** [comment]
I'm fine with that.

**Comment by zbeekman** [comment]
done, will include in a large, kinda mixed PR for FORD updates…

**Comment by zbeekman** [comment]
also, the test I added for this has gotten procedure level tests up to 100%.
