### ISSUE TITLE
JSON-FORTRAN —> JSON-Fortran?

### ISSUE THREAD

**Issue by zbeekman** [jacobwilliams/json-fortran#118]
What are your thoughts on moving to non-all-caps “Fortran” in “JSON-Fortran”? This would change references in the LICENSE and source files to JSON-Fortran rather than JSON-FORTRAN. I think in general it is a good idea to discourage the use of FORTRAN over Fortran, at least for modern code.

**Comment by szaghi** [comment]
:+1:

**Comment by jacobwilliams** [comment]
Agreed!
