### ISSUE TITLE
CHANGELOG.md

### ISSUE THREAD

**Issue by zbeekman** [jacobwilliams/json-fortran#120]
I think it would be [a good idea to keep a changelog](http://keepachangelog.com). There is an [automatic changelog generator](https://github.com/skywinder/github-changelog-generator) that can get us started, but it currently includes a lot of junk because closed (and some open) issues haven’t been tagged well. For example #108 has nothing to do with JSON-Fortran and should be labeled “invalid” or at least “question”.

**Comment by zbeekman** [comment]
The changelog can then contain links to the ROBODoc/FORD documentation for each release.

**Comment by szaghi** [comment]
Hi all, I am using the generator linked by @zbeekman . It is very nice and the main developer is vety kind and active. I vote for Zaak!

**Comment by zbeekman** [comment]
FYI, I am working on editing and paring down the changelog to reconstruct changes without the garbage added by the generator…. Should have that done soon.

**Comment by szaghi** [comment]
@zbeekman  What kind of *garbage* you are talking about?

**Comment by zbeekman** [comment]
@szaghi : just certain PRs, unlabeled issues, and poorly phrased issue titles. For example, there is no need to include a line in the changelog about adding waffle.io badges to the readme. That has no bearing on a change made to the actual software package. Also, when someone asked a question about Tecplot plots, which was completely unrelated.

Basically the output of the generator is a good starting place but:
 1. You need to be very disciplined about labeling your issues and PRs for it to contain the right information. (It looks at labels to determine what to include and how to include it.)
 1. The output is not dense enough. Each bullet point has it’s own paragraph, which takes up tons of screen realestate making it harder to quickly scan the changes
 1. PRs fixing specific issues don’t need their own sections, better to group them with issues they fix.
