### ISSUE TITLE
Wiki page for new version instructions

### ISSUE THREAD

**Issue by jacobwilliams** [jacobwilliams/json-fortran#122]
Need a wiki page with reminders about what to do when a new version is release. Homebrew, version number update in the CMake files, #120, etc.

**Comment by zbeekman** [comment]
Yes, this is a good idea… Hopefully most of the work can be automated but some might not, like Homebrew formula updates, bumping version number in CMakeLists.txt and some of the changelog stuff…

**Comment by zbeekman** [comment]
Also we should wait until we get the FORD documentation deployment setup.

**Comment by zbeekman** [comment]
I also want to stream line this to make it as easy as possible. I may try to find a way to put the version number in a file (like pypi packages do) and pull it in everywhere it’s needed from there. Then you just update it once and are good to go.

**Comment by zbeekman** [comment]
I’ve created a FORD “pages” page for this.

**Comment by jacobwilliams** [comment]
Looks great!!

**Comment by zbeekman** [comment]
close?

**Comment by jacobwilliams** [comment]
Yep.  I'm going to test it out...I hope it isn't too complicated for a poor Fortran person...

**Comment by zbeekman** [comment]
I hope it works! The main issue, is that using FORD and keeping a changelog makes it a little bit more complicated…. there are things that just end up having to be manually edited.
