### ISSUE TITLE
Travis builds failing

### ISSUE THREAD

**Issue by jacobwilliams** [jacobwilliams/json-fortran#127]
Did I break something in the recent merge?

**Comment by zbeekman** [comment]
What a flurry of activity! I probably can't look at this until the morning.

**Comment by zbeekman** [comment]
I think [this](https://github.com/jacobwilliams/json-fortran/commit/a18f026fad62489f781169b67ce8847fbaa6756f#diff-354f30a63fb0907d4ad57269548329e3L53) is the culprit… should have resolved the other way… let me just take a look at the travis log and make sure that that’s the only issue…
