### ISSUE TITLE
FORD and Codecov.io interaction

### ISSUE THREAD

**Issue by zbeekman** [jacobwilliams/json-fortran#131]
It seems that Codecov.io is reporting coverage info on the source file copied into `doc/` and something fishy is going on with reported coverage…

**Comment by zbeekman** [comment]
@jacobwilliams : I think that this can be resolved with the “ignore files” feature: https://codecov.io/github/jacobwilliams/json-fortran/features/ignore and adding `doc`. The list should now have two entries:
 1. src/test
 1. doc

**Comment by jacobwilliams** [comment]
Done.

**Comment by zbeekman** [comment]
I’m so confused as to why the coverage has now gone down even further…

Maybe we need to build it again for Codecov.io to update coverage? Or maybe we need to use the path fixer?

Also it seems like codecov.io is having some security issues, and because of this I was able to update the settings myself… I think we need a new push to get things sorted out, though…

**Comment by zbeekman** [comment]
OK, after some more digging, it seems that `--enable-unicode` breaks gcov. Essentially there is an off-by-one error for the correspondence between the execution count field and the remaining line number and source code fields in the `.gcov` file. Columns 2 and 3 need to be shifted down a row. See [this gist](https://gist.github.com/zbeekman/d08dc23555db10e2da48) with the bad output. Here is some awk magic to do that:

```awk
awk -F':' '{line=""; for(i=2;i<=NF;i++){line=line":"$i}; if (NR > 1) print $1 prevline; prevline=line}; END{print "        -"prevline}' json_module.F90.gcov
```

This corrects the off-by-one error. It was a real pain to figure out… Someone should submit a bug report to GCC/GFortran/GCov This also causes some very very odd output on Codecov.io. FTTB, it looks like we’re going to have to process the gcov file. If I were a betting man, I would guess that this has something to do with the preprocessing.

**Comment by zbeekman** [comment]
I currently have `build.sh` fix the gcov output if unicode is enabled. If/when gcov/gfortran fix this bug, the work around will end up causing an off-by one error (the other direction) to reappear.

> Note to future self: If the coverage info gets messed up for the unicode build, try removing the awk hackery from `build.sh`
