### ISSUE TITLE
Pass parts of JSON file to other subroutines

### ISSUE THREAD

**Issue by jacobwilliams** [jacobwilliams/json-fortran#133]
Question from @dugphd

Hi Jacob,

I absolutely love this json tool. I'm using it extensively and it has made a world of difference for my fortran code.

I've run into an issue that I can't figure out. I'm new to Github, so forgive me if this is not the correct place to ask questions:

After reading a json file, I'd like to pass parts of that file to other subroutines. Right now I'm doing this:
```fortran
type(json_value),pointer :: json_this, json_child
call json%get('run', json_this) !reads the "run" object from the file
call json_value_get(json_this,i,json_child) ! gets the "ith" child from the run object
call some_subroutine(json_child) !passes the child object to a subroutine
```
Within some_subroutine, I'd like to then pull out information from that child json object. For example, I'd like to get values out of it by name:
```fortran
call json_get(json_child, 'variable_name', value)
```
I've been hacking at this for quite some time and have not been able to get it to work. Do you have any ideas as to what I may be doing wrong?

Thanks.

**Comment by jacobwilliams** [comment]
Your approach should work.  I have done stuff like this before. Can you post the full code that is not working?  Otherwise, it's hard to say what the problem is.

**Comment by jacobwilliams** [comment]
Consider this example (run from the bin folder, and it opens one of the example files):

```fortran
program test

use json_module

implicit none

type(json_value),pointer :: p
type(json_file) :: json
logical :: found

call json_initialize()

call json%load_file(filename='../files/inputs/test2.json')
if (json_failed()) error stop 'error reading file'

call json%get('inputs',p,found)
if (.not. found) error stop 'error getting inputs'

call some_subroutine(p)

call json%destroy()

contains

 subroutine some_subroutine(d)
 
  use,intrinsic :: iso_fortran_env, only: real64
  
  implicit none
  
  type(json_value),intent(in),pointer :: d
  
  real(real64) :: x0
  
  call json_get(d,'x0',x0,found)
  if (.not. found) error stop 'error getting x0'
  write(*,*) x0
 
 end subroutine some_subroutine

end program test
```
The output is:
```
9999.0000000000000 
```
as expected.

**Comment by dugphd** [comment]
Jacob,

Thanks for the guidance. My code is several thousand lines long, so it will take some work to whittle it down to something I could post that displays the issue. But I'll explain my differences to what you are doing:

I have a main program that reads the file, and a separate subroutine (not in a "contains" statement) where I'm trying to pass the json object to. Both the main program and subroutine are including the json_module through inheritance of other modules. So the code compiles just fine and can find all necessary subroutines and commands.

Compiling is not an issue. But at runtime, I print the contents of the json object I'm trying to pass (let's call it p) from the main program, and it's fine. I pass p to the subroutine, and try to print it's contents, but it's empty. I believe I have everything declared correctly in both the main program and the subroutine.

Possible problems:
1. Does my subroutine have to be in a "contains" statement with the main program for this to work (like your example)?

2. Do I have to rerun json_initialize() within the subroutine for some reason?

Thanks for your help. I'll try to whittle my code down to something that can be posted.

**Comment by jacobwilliams** [comment]
Hmmm, I'm not sure what the problem could be.

The "contains" is not necessary for it to work, that's just how I did it for this example. Having different modules should work fine.

```json_initialize()``` only needs to be called once.

Note: to test for errors in the JSON module, you can use the ```json_failed()``` function, and also get the error message using the ```json_check_for_errors()``` subroutine.  Note that, if an exception has been thrown, a lot of the routines in the module will return without doing anything, so you should check for errors if there is the possibility that something might go wrong. Perhaps that is what is happening?

**Comment by dugphd** [comment]
Finally found the problem. For some reason, my subroutine needed to be inside of a module. I found the error by trying to write a short example code to show the issue, and got an error about not explicitly defining the subroutine. So this uncovered the larger problem of needing the subroutine in my actual code to be within a module.

In short, it's working now and is awesome! Thanks so much for helping me find the bug.

**Comment by jacobwilliams** [comment]
Oh, yes, I think that makes sense. In general, it is good practice in modern Fortran for everything to be in a module (this provides an automatic explicit interface for all the subroutines and functions). There are some features that require this interface. I believe an explicit interface may be required for pointer arguments (such as the ```json_value``` pointer in this case).

**Comment by zbeekman** [comment]
Should we close this issue?

Also, @jacobwilliams, I may add methods to cast `json_value` objects as `json_file` objects and vise-versa. There's no reason, as far as I can tell, why you couldn't initialize a `json_file` object from a `json_value` object or extract the `json_value` component of a `json_file` object, no?

**Comment by jacobwilliams** [comment]
Yes, that's a good idea.

**Comment by dugphd** [comment]
Awesome. Thanks for your help. Yes, I got it working and this case can be closed.

I second the json_value -> json_file and vice versa. That would be really helpful to me.

Thanks guys!

**Comment by zbeekman** [comment]
@jacobwilliams : In the context of type casting, we need to think carefully about data hiding, encapsulation and interfaces. I’m conflicted on whether to copy the objects (at least a shallow copy, but maybe a deep copy) when casting, vs just using pointer assignment. The `json_file` type seems to have more data hiding and encapsulation with more automatic memory management, whereas the `json_value` type seems work through explicit knowledge of the underlying pointer based json object structure.

I’m tempted to implement the type casting as the most flexible, but more difficult to reason about pointer reference variation: For the casting procedures, pointers will be used to point to the `json_value` object. So when you cast a `json_file` object as a `json_value` object, a pointer is returned like `result => this%p` and when you cast a `json_value` as a `json_file` you create a *new* `json_file` object, but with `p` pointing to the `json_value` object: `my_json_file = json_file(value=my_json_value_object) ! overloaded structure constructor, provides write access to %p`

The downside of this is that `json_file` objects state and structure will now be mutable from outside calls to type bound procedures. The alternative to this, would be to perform deep copies: deep copy `this%p` to a new `json_value` object or deep copy the `json_value` object to `this%p`. This previous implementation is trivial, where as this implementation will take considerable work…
