### ISSUE TITLE
way to traverse JSON structure without knowing it a priori?

### ISSUE THREAD

**Issue by zbeekman** [jacobwilliams/json-fortran#140]
I’m wondering if there is currently a method to easily traverse a json structure. Suppose you wish to read a file, `mystery.json` whose structure is unknown to you at the time you are writing the code to read it?

I was looking at your [TOPOSORT blog post](http://degenerateconic.com/topological-sorting/) and got to thinking: a JSON file/structure is a DAG! (In fact, when you print a JSON structure you have to linearize it first!) 

Right now, the only procedures I see to query JSON nodes require either: a) The path, which is not known *a priori* or b) a pointer to the node. An iterator pattern would be useful to traverse JSON objects of unknown structure. TOPOSORT could be used to linearize a JSON object as a linked list, and then this could be iterated.

```fortran
do
    call json_iterate(root,current,finished) ! statefu (need save variables)
    if ( finished ) then
        call json_iterate(root,current,finished,reset=.true.)
        exit
    end if
    ! process current
end do
```

The same idea could be achieved with the reverse communication pattern too (callback procedures)

```fortran
abstract interface
    subroutine process_element_callback(this)
        import :: json_value
        type(json_value), pointer, intent(out) :: this
    end subroutine
end interface
…
do
    call json_process(root, things_to_do, finished)
    if ( finished ) exit
end do
```

**Comment by jacobwilliams** [comment]
This is interesting...need to think about it some more.  What would be an application for this?

Currently, I would do this by using ```json_info``` to query the data type, and how many children it has, etc, and then step through things using ```json_value_get_by_index```.

**Comment by zbeekman** [comment]
Well, I was reading about YAML, and how one of its main features/design-goals/uses is to represent data structures from programs and be able to write them to disk or recreate them from the YAML file. In general JSON isn’t quite as flexible and well suited for that, but there are applications where it might be of utility to read in some JSON file and then walk through it, visiting every node, without knowing a priori what the JSON structure is. Perhaps the JSON file represents a general data-base, and you want to search it in its entirety for a given item. Or maybe the JSON file is used to describe a data format (like XML is used in [Xdmf](http://www.xdmf.org/index.php/Main_Page)) and you’re looking for a particular part of the data set but you don’t know where it is. Or maybe you need to perform some sort of transformation on all of the data in the file, like convert from SI to Imperial/US customary units…

**Comment by jacobwilliams** [comment]
What do you think? This is basically the callback approach.

**Comment by zbeekman** [comment]
Looks good to me!
