### ISSUE TITLE
ford failing on json_module on Travis

### ISSUE THREAD

**Issue by jacobwilliams** [jacobwilliams/json-fortran#148]
The error is [```Found procedure call in MODULE```](https://travis-ci.org/jacobwilliams/json-fortran/jobs/77440478#L3452). Not sure why this is happening.

**Comment by jacobwilliams** [comment]
The behavior is different on [TravisCI](https://travis-ci.org/jacobwilliams/json-fortran/jobs/77440478#L3452) than on my Mac, where it works fine.  @zbeekman or @cmacmackin any ideas?

**Comment by zbeekman** [comment]
On vacation, but I may have a chance to look tomorrow otherwise I will try to take a look early next week

**Comment by zbeekman** [comment]
Looking at it on my phone, and thinking back, I wonder if there is a name clash with an intrinsic? AFAICT Travis is running the latest version (4.2.1) of FORD. I vaguely recall a variable (ilen?) that had the same name as an intrinsic. Maybe you're running an older version of FORD on your laptop and recent added intrinsic support is finding the issue?

**Comment by cmacmackin** [comment]
That message means that FORD has misidentified something within the declarations component of the module as a function call. I'm aware of this bug and plan to release a fix for it (as well as some others introduced with tracking of function calls) ASAP.

**Comment by cmacmackin** [comment]
The latest version of FORD should have fixed this problem.

**Comment by jacobwilliams** [comment]
Yep! Thanks!
