### ISSUE TITLE
Public APIs for creating a JSON structure

### ISSUE THREAD

**Issue by jacobwilliams** [jacobwilliams/json-fortran#15]
Consider removing the necessity of having to use pointers to construct a JSON structure for writing.  This could be done by encapsulating the pointer inside a class (as was done for json_file).

**Comment by zbeekman** [comment]
Was this covered in the 5.x release?

**Comment by jacobwilliams** [comment]
Eh, sort of. I think I was thinking of something more grandiose at the time, but I think what we have now is fine. I'm going to close it.

**Comment by jacobwilliams** [comment]
See also: #257
