### ISSUE TITLE
Better name for "FORD pages" documentation?

### ISSUE THREAD

**Issue by zbeekman** [jacobwilliams/json-fortran#150]
Right now, the menu bar for the FORD generated documentation breaks onto a new line. This may be due to the fact that the "FORD pages" entry, "Additional Documentation" is rather long, taking up too much space. Perhaps we should think of something more succinct to name this section.

**Comment by jacobwilliams** [comment]
Additional Docs, Other Docs, ... I don't have any strong preferences.

**Comment by zbeekman** [comment]
Yeah, they all sound a bit imprecise and informal, but short of thinking of something brilliant, "other docs" sounds best to me.
