### ISSUE TITLE
how to build unit tests with cmake?

### ISSUE THREAD

**Issue by floswald** [jacobwilliams/json-fortran#154]
hi there,

I did 

```bash
mkdir build
cd build
cmake ..
ctest
```

but it doesn't run any test, saying, e.g. `Unable to find executable: ./jf_test_9`. what did I do wrong? thanks.

**Comment by jacobwilliams** [comment]
Question for @zbeekman. I've never tried to build it with cmake.

**Comment by zbeekman** [comment]
Hi @floswald, we moved to a system to emulate GNU auto-tools more closely.

First a question, what generator are you using? Right now, only the Makefile generator is supported.

To build and run the unit tests:

```
mkdir build
cd build
ccmake .. # configure settings etc., and be sure to generate build system before quitting
make check # will build library and unit tests, then run them with test
# `make` will build the library but not the tests
```

If you have any further questions or concerns let me know...

**Comment by floswald** [comment]
excellent! thanks a lot. (maybe a comment on the readme would be helpful for that).

**Comment by adamjstewart** [comment]
Would it be possible to make the `test` target an alias to the `check` target so both `make check` and `make test` work?

**Comment by zbeekman** [comment]
@adamjstewart you cannot re-define CMake default targets. `test` is an extant target, and there is no way to redefine it. There is an additional target to build the tests without running them. Building this target and then the `test` target will work as expected.
