### ISSUE TITLE
How to access json object which has space etc in its name

### ISSUE THREAD

**Issue by zmiimz** [jacobwilliams/json-fortran#155]
Is it possible with json-fortran to access object with spaces and brackets in its name?  Seems to be valid json format...

{
    "parameters": {
        "mass [kg]": 09,
        "volume [L]": 100
    }
}

**Comment by jacobwilliams** [comment]
Yes, it is possible. Since they have brackets, you can't use the normal parsing routines (which assume the brackets denote arrays). You would have to traverse the structure manually using ```json_value``` pointers and the ```json_get_child``` routine.  Example is below:

```fortran
program test

use json_module
use iso_fortran_env, only: wp => real64

implicit none

type(json_file) :: json
type(json_value),pointer :: parameters,p
real(wp) :: mass,volume
logical :: found

call json_initialize()  !initialize the module
call json%load_file(filename='test.json')  !load the file

!pointer to the parameters structure:
call json%get('parameters',parameters,found)

!get each child variable as a pointer, and 
!then extract the value:
call json_get_child(parameters,'mass [kg]',p)
if (.not. associated(p)) error stop 'mass not found'
call json_get(p,mass)

call json_get_child(parameters,'volume [L]',p)
if (.not. associated(p)) error stop 'mass not found'
call json_get(p,volume)

!cleanup:
call json%destroy()

write(*,*) 'mass=',mass
write(*,*) 'mass=',volume

end program test
```

However, my recommendation would be to make variables where the units are a separate string in the structure. Something like this:

```json
{
    "parameters": {
        "mass": {
            "value": 9,
            "units": "kg"
        },
        "volume": {
            "value": 100,
            "units": "L"
        }
    }
} 
```

**Comment by jacobwilliams** [comment]
Note: the spaces shouldn't cause any special problems.

OK to close?

**Comment by zmiimz** [comment]
Yes,
many thanks!

**Comment by jacobwilliams** [comment]
Note: now you can use `path_mode=2` to specify paths using [RFC6901](https://tools.ietf.org/html/rfc6901) format, which will work for all names.
