### ISSUE TITLE
Bug reading scientific notation

### ISSUE THREAD

**Issue by dwsideriusNIST** [jacobwilliams/json-fortran#157]
Currently, json-fortran incorrectly reads certain real numbers given in scientific notation.

For example, given this input JSON file:
```json
{
	  "real1" : 1.000000E-05,
	  "real2" : 1.E-5,
	  "real3" : 1E-5
}
```
and this fortran program:
```fortran
program test_JSON
USE json_module
IMPLICIT NONE
CHARACTER(100) :: argv
LOGICAL :: input_JSON, found
INTEGER :: istat, intno
REAL :: realno
type(json_file) :: json
call get_command_argument(1,argv,istat)
call json%load_file(filename = argv)
IF (json_failed()) THEN
   WRITE(*,'(A)') 'ERROR: FAILED WHILE LOADING JSON FILE: '//TRIM(argv)
   STOP
ELSE
   WRITE(*,'(A)') 'SUCCESSFULLY OPENED JSON FILE: '//TRIM(argv)
   call json%get('real1', realno, found)
   write(*,*) realno
   call json%get('real2', realno, found)
   write(*,*) realno
   call json%get('real3', realno, found)
   write(*,*) realno
ENDIF
end program test_JSON
```
the output is:

  1.000000000000000E-005
  1.000000000000000E-005
  9.999999999999999E-022

Note: the "real3" value is "1e-5", but is read as 1e-22 (effectively zero). The other two versions of "0.00001" are read correctly.

I submit this as an issue because Python, with the standard json package, will output real numbers as 1e-5 rather than 1.0e-5.

Can json-fortran be fixed to read this type of real number correctly?

**Comment by jacobwilliams** [comment]
I'll look into it...

**Comment by zbeekman** [comment]
I'm not sure if this is a bug or expected behavior. If it is a bug I may have been the culprit for introducing it.

**Comment by dwsideriusNIST** [comment]
This bug has existed for a long time. It was in a build of json-fortran from April 2014 as well as the latest version.

It only cropped up because the real number output in Python changed - "0.00001" used to be output as "1.e-5", but now it is output as "1e-5". I use Python to generate the JSON input files for my Fortran programs.

**Comment by jacobwilliams** [comment]
The cause is this line in ```string_to_double```:
```fortran 
read(str,fmt=real_fmt,iostat=ierr) rval    !string to double
```
It looks like strings of the form ```'1E-5'``` aren't read properly using fmt statements like ```(E26.16E4)```. I'm not sure if this is expected behavior or not? If I replace it with '*' fmt, it works, but I need to make sure that doesn't break anything else.

**Comment by jacobwilliams** [comment]
I committed the fix. I'll do a new release version soon. Thanks for the bug report!

**Comment by zbeekman** [comment]
I like the addition you made @jacobwilliams parsing for the default edit descriptor... @dwsideriusNIST : you'll have to pass a custom edit descriptor to `json_initialize`e.g., `call json_initialize(real_format='*')` to implement the current fix. I'm also curious what happens if you try the "g" edit descriptor with your test case: `call json_initialize(real_format='g#.#e#')` where the `#` is replaced with something sensible. If this works maybe we can change the default real edit descriptor from `e` to `g` allowing `1e-3` notation...

**Comment by jacobwilliams** [comment]
I tried a couple different ones and couldn't get it to work (maybe there's a way... I admit I'm not sure why it doesn't work). 

But, note: the fix works even if you don't use ```json_initialize(real_format='*') ```.  That only affects how the real numbers are printed, not how they are read (which is now always ```fmt=*```).

**Comment by zbeekman** [comment]
Ahhh, I see, sorry I read your patch too quickly. I'm surprised `g` doesn't work...
