### ISSUE TITLE
String parsing bug

### ISSUE THREAD

**Issue by jacobwilliams** [jacobwilliams/json-fortran#164]
There appears to be a bug when parsing a string that ends with `\\`.  Example:
```json
{
    "str": "blah\\"
}
```
Look into this.

**Comment by jacobwilliams** [comment]
Probably something in `json_get_string`.  Need to rewrite the logic in that routine.

**Comment by zbeekman** [comment]
Let me know if/when you publish a new release and I can update the Homebrew Formula.

**Comment by jacobwilliams** [comment]
Will try to do that soon.

**Comment by zbeekman** [comment]
oops.. I'm duplicating my own messages, sorry.
