### ISSUE TITLE
4.3.0 release

### ISSUE THREAD

**Issue by jacobwilliams** [jacobwilliams/json-fortran#167]
Working on this now...

**Comment by zbeekman** [comment]
I should really work on scripting the homebrew formula update for simple releases... If we install [hub](https://github.com/github/hub) on travis, it is conceivable that we could script this... I saw some automation of this here: https://github.com/Homebrew/homebrew/issues/46580

**Comment by jacobwilliams** [comment]
Release published.

Yes, automating the homebrew formula would be great!

**Comment by zbeekman** [comment]
Homebrew formula updated and merged by homebrew
