### ISSUE TITLE
Split into multiple files?

### ISSUE THREAD

**Issue by jacobwilliams** [jacobwilliams/json-fortran#168]
Thinking about splitting the module into multiple files (maybe separate modules for `json_value`, `json_file`, general utilities, etc.) See also Issue #36. Having everything in one file can be convenient for users, but is starting to get unwieldy for development purposes.

**Comment by zbeekman** [comment]
I support the idea, FWIW. If you need help wrangling the build system as you work, let me know.

**Comment by jacobwilliams** [comment]
Yes, likely I will need help! I'm going to get back to working on json-fortran soon, and this one and #36 are my top priorities, so there will be a lot of changes.

**Comment by zbeekman** [comment]
:+1:

**Comment by jacobwilliams** [comment]
Started working on this...

**Comment by jacobwilliams** [comment]
I think it's done. Currently CMake is broke, and coverage is broke (note that I deactivated coverage from the travis.yml file just to see if the build.sh test would pass, which it does, so that will need to be reenabled). See PR #170. @zbeekman, the ball is in your court. :)

**Comment by jacobwilliams** [comment]
Also started on #36. Note that [thread-safe](https://github.com/jacobwilliams/json-fortran/tree/thread-safe) is branched off of [split](https://github.com/jacobwilliams/json-fortran/tree/split). I might be overestimating my git skills though...

**Comment by zbeekman** [comment]
I will try to attend to this as soon as I can, but I am a bit swamped at the moment

**Comment by jacobwilliams** [comment]
No problem. No rush at all!

**Comment by jacobwilliams** [comment]
I went ahead and merged it all to master. Will make a new issue for the coverage (I believe I fixed the CMake build).
