### ISSUE TITLE
Rename parameters RK, IK, ... using less generic names

### ISSUE THREAD

**Issue by libuda** [jacobwilliams/json-fortran#172]
Hi,

I am using your JSON FORTRAN module within an old Fortran code that uses massively COMMON blocks to communicate between the different program parts. Everything works out fine except that I had to refactor the old code as it was using variables like RK and IK in COMMON blocks and throughout the code. I am wondering whether it would make sense to rename the JSON FORTRAN parameters using less generic names where the chance is high that these names are already in use by the calling program. 

E.g. one could replace RK by RK__, i.e. add two underscores 
````fortran
    module json_module
    use,intrinsic :: iso_fortran_env
    implicit none
    private
    integer,parameter :: RK__ = real64  !! Default real kind [8 bytes]
    integer,parameter :: IK__ = int32   !! Default integer kind [4 bytes]
...
 ````
What do you think?

Regards, Volker
P.S.: I appreciate your effort. Thanks for writing, maintaining and improving the code :+1:

**Comment by jacobwilliams** [comment]
Yes, you are right, they should probably be less generic. I'm in the process of a major refactor, so I can do something along these lines as well.

Note: you can also rename them when you use the module like so:

````fortran
    use json_module, RK_ => RK
    integer(RK_) :: r
    integer :: RK ! now you can use this for whatever you want
````

**Comment by zbeekman** [comment]
I was about to suggest doing what @jacobwilliams suggested...

As for renaming, it might be wise to add some string  to all public entities,  like `JF_`  prefix or something...  but this will increase verbosity. Also, scrutinizing what entities are publicly exposed might also be a good idea.... Do we need to expose RK and IK?

**Comment by jacobwilliams** [comment]
Maybe they don't really need to be public. In the ```split``` branch, these variables have been moved into a ```json_kinds``` module. So, maybe that one is not required to be used on the user side, but if you want to use it you can (for whatever reason)?

**Comment by jacobwilliams** [comment]
Also note: in the ```thread-safe``` branch, there are now really only three public entities: ```json_value```, ```json_file```, and ```json_core```.  So, we could do ```json_RK```, etc... (and of course, you can rename them to be whatever you want, as shown in the above example).

**Comment by jacobwilliams** [comment]
Proposed solution [here](https://github.com/jacobwilliams/json-fortran/commit/7a426861aa8ffc70aa0f9bd2d3b4d23f7afa3468#diff-e6c51f151d46143f0b0b7655eaf47de3L37).

**Comment by zbeekman** [comment]
@libuda were you able to test the fixes on master?

**Comment by libuda** [comment]
I am currently on vacation in Valencia, Spain. Great city for a lot of stuff but not for checking enhancement request. :)  Will do when I am back to work next week.

**Comment by zbeekman** [comment]
No worries, enjoy your trip.
