### ISSUE TITLE
Code coverage broken

### ISSUE THREAD

**Issue by jacobwilliams** [jacobwilliams/json-fortran#174]
Since the recent splitting of json_module into multiple files, the code coverage generation is currently broken. I [temporarily disabled it in the unit tests](https://github.com/jacobwilliams/json-fortran/commit/a32204c1549789269957e64d88fa65815c1c47f9#diff-354f30a63fb0907d4ad57269548329e3) just so they would pass, but it should be fixed.

**Comment by zbeekman** [comment]
To further complicate things, codecov.io just migrated to a config file based settings... the mapping/documentation between the old and new system is not 100% obvious, so I'll have to poke around a bit.

**Comment by jacobwilliams** [comment]
I started tinkering with it a bit...see [codecov](https://github.com/jacobwilliams/json-fortran/tree/codecov) branch. Not finished. Whenever you get a free moment, you may have to clean up whatever mess I end up creating. :)

**Comment by zbeekman** [comment]
Haha fair. Yeah it looks like I won't be able to get to this this week. Hopefully next.

**Comment by jacobwilliams** [comment]
I think I've got it! I'll keep the ticket open and double check everything this week sometime.

**Comment by zbeekman** [comment]
Ok great. I'll try to get eyes on it when I can.

**Comment by jacobwilliams** [comment]
Not sure what `codecov/changes — 2 files have unexpected coverage cha...` error is all about in PR #195. I think perhaps because the changes are in the unit test files, which we are logging coverage for?

**Comment by zbeekman** [comment]
The codecov upgrade has been a bit of a dog's breakfast. This one message
was created because the #1 support request used to be hunting down changes
"that should not have appeared". In my opinion this "feature" is likely
going to cause 10x more support requests for them from people who know what
they're doing and are confused/annoyed/offended by this asinine error. Yes
my coverage changed, but, no, it is not unexpected and it most certainly is
not an error.

**Comment by zbeekman** [comment]
(Btw your suspicion is right, it's generated when coverage changes without
touching parts of the code where this happened, I.e. Doing anything with
unit tests)

**Comment by jacobwilliams** [comment]
Ug. We need to disable the ability of Codecov to cause a test failure. I haven't had a chance to look into it further, but it looks like every commit now fails because of this. I don't like seeing all those red X's!

**Comment by jacobwilliams** [comment]
Maybe this is magically fixed now? My last commit to #206 has coverage tests passing...

**Comment by zbeekman** [comment]
yes, the pass/fail is trying to programmatically enforce coverage metrics i.e. certain minimum global coverage and coverage changes allowed by the commits, i.e. coverage can't decrease etc. Just a matter of finding the right settings and/or poking around the github project settings to turn off codecov pass/fail

**Comment by jacobwilliams** [comment]
Reduced target coverage to 70% for now. Closing issue, but we can fiddle with the settings some more if necessary.
