### ISSUE TITLE
github issue/PR templates?

### ISSUE THREAD

**Issue by zbeekman** [jacobwilliams/json-fortran#178]
Any interest in issue and PR templates?
https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by zbeekman** [comment]
ping @jacobwilliams

**Comment by jacobwilliams** [comment]
No strong opinion either way. I'd be OK with it.

**Comment by zbeekman** [comment]
yeah I guess it's fairly low traffic, because people don't seem to find many bugs or other issues 😄 

No point making more work for myself, I'll close this.
