### ISSUE TITLE
expand test matrix?

### ISSUE THREAD

**Issue by zbeekman** [jacobwilliams/json-fortran#180]
We can expand the test matrix to OS X, Ubuntu 14.04 pretty easily... We could also try to build a linux docker image using the free Intel compiler, as well as trying the free OS X PGI compiler....

I'll put this on my someday list

**Comment by szaghi** [comment]
@zbeekman 

I am interested to learn how setup a docker image with Intel compiler (free????), can you send some references?

You (Zaak, Jacob...) are always sources of inspiration!

See you soon.

**Comment by zbeekman** [comment]
@szaghi I haven't tried it yet, and you'll have to roll-your-own but here are the relevant links:
Please note, you may not be legally allowed to use the Intel Compilers depending one what the project is and what your relationship to it is.

https://software.intel.com/en-us/qualify-for-free-software/opensourcecontributor
https://docs.travis-ci.com/user/docker/
https://docs.docker.com/linux/

You can build docker images locally, even if they take a very long time, and then upload them to docker hub (https://hub.docker.com) then use the images in your build on travis-ci... There are still a few concerns I have about licensing ifort... and making sure that you're not accidentally distributing a docker image with it installed to the whole world... more research is needed

**Comment by szaghi** [comment]
@zbeekman very interesting, thank you for sharing these resources!

**Comment by jacobwilliams** [comment]
Another thought: would it be desirable to also test multiple versions of gfortran? (4.9, 5, 6,...). Currently we only test against 4.9 on Travis (and I usually will update locally to whatever the latest version it), so the intermediate versions are never tested.

**Comment by zbeekman** [comment]
I think this is doable... if you want a fast/responsive turnaround, you're limited by which packages are whitelisted... I know 6.1 and (and probably 5.2 or 5.3) are in ubuntu/toolchain-r-test PPA which IS whitelisted... so we could test 4, 5 and 6 I think.

**Comment by zbeekman** [comment]
A bit swamped at the moment, but hopefully I can help out soonish

**Comment by zbeekman** [comment]
Different versions of GFortran is pretty low hanging fruit. I'll try to get to that soon.
