### ISSUE TITLE
GFortran 6

### ISSUE THREAD

**Issue by jacobwilliams** [jacobwilliams/json-fortran#186]
The current master branch does not compile with [Gfortran 6.1 on a Mac](http://coudert.name/software.html). Error message is:

````
./src/json_string_utilities.F90:287:0:

                 str_out = str_out(1:ipos-1)
 
internal compiler error: in expand_expr_real_1, at expr.c:9651

./src/json_string_utilities.F90:287:0: internal compiler error: Abort trap: 6
gfortran: internal compiler error: Abort trap: 6 (program f951)
````
A compiler bug I guess?

**Comment by zbeekman** [comment]
What, the actual f*** GCC... sigh

This is not even close to being a real (float) expression... and should be perfectly valid with realloc lhs.

I am actually in the process of submitting a PR to upgrade Homebrew's GCC to 6.1, and JSON-Fortran is one of the packages that will need to be rebuilt with the upgrade... however, until we publish a new release with a work around, it looks like we'll just be adding a `fails_with => :gcc "6"` to the formula for the time being...

**Comment by zbeekman** [comment]
@jacobwilliams oh, actually, have you tried building the latest release with GCC 6.1? (not master)

**Comment by zbeekman** [comment]
I suspect that we may need to allocate a temp, and then move_alloc it to the actual variable.

**Comment by jacobwilliams** [comment]
Will try this soon.

**Comment by jacobwilliams** [comment]
And no, the last release (4.3.0) doesn't compile with gfortran 6.1 (same bug).

**Comment by zbeekman** [comment]
We should file a bug report too... I've been pretty busy with open coarrays and work, sorry I haven't had much time to devote to this

**Comment by danilaml** [comment]
Was this bug ever fixed/reported? Also, would it make sense to only "ifdef" affected version instead of all gfortran compilers?
