### ISSUE TITLE
Gfortran bugs

### ISSUE THREAD

**Issue by jacobwilliams** [jacobwilliams/json-fortran#190]
There are a couple of instances of workarounds for gfortran bugs related to deferred-length character strings. These have a non-zero impact on runtime speed. Add some compiler directives so that non-gfortran builds can be more efficient. (See 677345e)

**Comment by zbeekman** [comment]
Which other work arounds impact performance?

**Comment by jacobwilliams** [comment]
All the ones where we have unnecessary string allocations will cause a performance hit (maybe small, but every little but helps).
