### ISSUE TITLE
5.0 Release Notes

### ISSUE THREAD

**Issue by jacobwilliams** [jacobwilliams/json-fortran#200]
The next release will be 5.0, and will include all the recent changes to make the library thread safe. There are a lot of changes, and it breaks backward compatibility. Maybe should write up a short note (on the main readme or Wiki) with some examples on converting older pre-5.0 code.

**Comment by jacobwilliams** [comment]
Working on 5.0 conversion notes [here](https://github.com/jacobwilliams/json-fortran/wiki/5.0-Changes).

**Comment by zbeekman** [comment]
How hard would it be to back port the gcc 6 work around (and any other bug fixes) onto the 4.x branch? I ask because it could be nice to allow users not ready to upgrade to 5.0 to build with gcc 6.

**Comment by jacobwilliams** [comment]
It's a minor change. I could do that as a 4.3.1 release. Probably would want to manually edit the documentation files to avoid confusion so that it comes before 5.0, since the auto-deployment scripts will put a newer release at the top of the list right?
