### ISSUE TITLE
Adding "default" value to json%get

### ISSUE THREAD

**Issue by jacopo-chevallard** [jacobwilliams/json-fortran#208]
I was wondering if you think worth/interesting adding a `default` optional argument to the `json%get` methods, i.e. instead of having

``` fortran
        call json%load_file(filename = 'test.txt')
        call json%get('foo', i, found)
        if (.not. found) i = default_foo
```

we would have

``` fortran
        call json%load_file(filename = 'test.txt')
        call json%get('foo', i, default=default_foo)
```

Where the optional `found` and `default` arguments should not be present at the same time.

Using the first option is completely fine (just 1 more line of code), but I think that the code would appear clearer by either using the `found` argument, which implies that one expects the `foo` key to be present in the JSON structure, and by using the `default` one, which relaxes this requirement.

**Comment by jacobwilliams** [comment]
Interesting. Yes, this could be added. I would think to allow both `found` and `default` at the same time, since you still might want to know if it was there or not.

**Comment by jacopo-chevallard** [comment]
You may find interesting this simple equation parser https://github.com/jacopo-chevallard/FortranParser (I just re-wrapped in Fortran 2008 OOP [fparser](http://fparser.sourceforge.net)).

With this, and JSON-Fortran, it becomes trivial to read and parse equations/variables at runtime into a Fortran program, i.e.
```fortran
type(json_file) :: json
type(EquationParser) :: eqParser

jsonString = '{"variables" : ["x", "y"], "function" : "2*x+sin(y**2)"}'
call json%load_from_string(jsonString)

call json%get('function', func, found)
call json%get('variables', vars, found)

eqParser = EquationParser(func, vars)

value = eqParser%evaluate([2., 5.])
value = eqParser%evaluate([-2., -5.])
```

**Comment by jacobwilliams** [comment]
Terrific!! At one point I was also working on updating fparser with modern Fortran stuff (I think I was also adding the ability to have vector variables). I don't think I ever finished it. I'll take a look at yours and maybe revisit it at some point.

**Comment by jacopo-chevallard** [comment]
:) for now I really did minimal modifications to the original fparser, just to allow me to use it in OOP, avoiding the SAVEd variables upon which fparser was based! But it does what it's supposed to...

**Comment by desperadoshi** [comment]
Hi! For those people looking for the default argument in the subroutine get, I have done minor changes to enable this feature. Check my [forked repo](https://github.com/desperadoshi/json-fortran#note). I will not put it in the pull request. Because I think it is a temporary solution and not beautiful.

**Comment by jacobwilliams** [comment]
I think this is basically ready to go. All the "get by path" routines have a `default` optional input like so:
```fortran
  call json%get('foo', i, found, default=default_foo)
```
