### ISSUE TITLE
dot files?

### ISSUE THREAD

**Issue by jacobwilliams** [jacobwilliams/json-fortran#211]
Was wondering if we should change some of these files in the root that a user doesn't really care about to start with `.`? So: `__VERSION__` to `.version` and `preprocessor-def.md` to `.preprocessor`. Also, I think `CONTRIBUTING.md` can go in a `.github` directory and GitHub will still know what to do with it.

**Comment by zbeekman** [comment]
Fine with me.  You can also create release artifacts with `git archive` and exclude these types of files in a `.gitattributes` file.
