### ISSUE TITLE
Printing without line breaks

### ISSUE THREAD

**Issue by jacobwilliams** [jacobwilliams/json-fortran#216]
Add option for printing without line breaks (if you wanted to print the entire JSON structure to only one line). Would likely be an optional argument to the `initialize` routines.

**Comment by zbeekman** [comment]
What's the point of this? Minification?

**Comment by jacobwilliams** [comment]
Exactly. I wanted the option to generate the smallest file possible and still be valid. So, no linebreaks or extra whitespace, etc.
