### ISSUE TITLE
Outputting arrays on a single line

### ISSUE THREAD

**Issue by milancurcic** [jacobwilliams/json-fortran#228]
Hi Jacob et al.,

Thank you for the amazing work on json-fortran. I did a brief search through the code and the docs and I couldn't find an answer - can json-fortran output an array on a single line? For example, this:

``` fortran
call json % initialize()
call json % create_object(ptr,'')
call json % add(ptr,'value',[1._rk,2._rk,3._rk])
call json % print(ptr,'test.json')
call json % destroy(ptr)  
```

outputs this:

``` json
{
  "value": [
    0.1E+1,
    0.2E+1,
    0.3E+1
  ]
}
```

However, I would like this:

``` json
{
  "value": [0.1E+1, 0.2E+1, 0.3E+1]
}
```

with the goal of minimizing file size once I start writing very large arrays. `json_file % load_file()` seems to be happy with reading single-line arrays.

**Comment by jacobwilliams** [comment]
You can minimize the whole file by using `no_whitespace`, but there is no option just to do it for arrays. Maybe I could add it. I guess the logic would be once an array was started, to turn off all line breaks until the array ends? I'd need to look at the code.

**Comment by szaghi** [comment]
What about *turn all new lines off* (not only the array ones)? If you can *parametrize* the newline character with a variable to be initialized with an optional dummy at the very early phase (e.g. `json%initialize(minify=.true.)`) the modification of the actual code should be *few&simple* (e.g. `sed 's/new_line("a")/newline/' *f90` where `newline` is your initialized variable that, if `minify=.true.` is srt to `newline=''` instead of `newline=new_line('a')`). Just an hint.

Cheers.

**Comment by jacobwilliams** [comment]
`json%initialize(no_whitespace =.true.)` basically does exactly that. But currently it's for the whole file. So, the following file:

```json
{
	"t": 0.0E+0,
	"x": [0.1E+1, 
          0.2E+1,
          0.3E+1],
	"m": 0.2E+4,
	"name": "foo"
}
```
would be written as:
```json
{"t":0.0E+0,"x":[0.1E+1,0.2E+1,0.3E+1],"m":0.2E+4,"name":"foo"}
```
What I think Milan was wanting was this:
```json
{
	"t": 0.0E+0,
	"x": [0.1E+1, 0.2E+1, 0.3E+1],
	"m": 0.2E+4,
	"name": "foo"
}
```
Is that right?

**Comment by milancurcic** [comment]
@jacobwilliams Exactly. Minifying with `no_whitespace` will be very useful, but some files I would still prefer to be human readable.

**Comment by zbeekman** [comment]
One tricky thing is you can have arrays of structures so what effect will it have in that case.

Btw if you haven't seen it yet, jq is an amazingly powerful DSL that is like AWK or sed for JSON. Not Fortean but good for quick and dirty shell manipulation of JSON data.

**Comment by milancurcic** [comment]
> One tricky thing is you can have arrays of structures so what effect will it have in that case.

I don't know! :)

**Comment by szaghi** [comment]
>json%initialize(no_whitespace =.true.) basically does exactly that. 

Sorry, I never tried it, I was not aware it clean also newlines :cry:

**Comment by zbeekman** [comment]
> I don't know! :-)

It might not be soon bad/hard to implement since I think the library can tell pretty easily whether it's an array of primitives or not. Could jus remove new lines when array of primitives. This would also be helpful for arrays of arrays (matrices). Ok I need to sleep now. Survived the debate... phew)

**Comment by zbeekman** [comment]
Gah can't edit previous post on mobile. Soon -> too

**Comment by jacobwilliams** [comment]
The routine that would need to be modified is `json_value_print`. I can try to take a look, maybe later in the week.

**Comment by jacobwilliams** [comment]
Working on this. Need to make some unit tests and then will merge it into master.

**Comment by jacobwilliams** [comment]
Setting `compress_vectors=.true.` in `initialize()`, the following JSON structure:
```json
{"int_vec":[1,2,3],"int":1,"object":{"int_vec":[1,2,3]},"vec":[[1,2],[3,4]],"vec_of_objects":[{"a":1},{"bvec":[1,2,3]}]}
```
will now print as:
```json
{
  "int_vec": [1, 2, 3],
  "int": 1,
  "object": {
    "int_vec": [1, 2, 3]
  },
  "vec": [
    [1, 2],
    [3, 4]
  ],
  "vec_of_objects": [
    {
      "a": 1
    },
    {
      "bvec": [1, 2, 3]
    }
  ]
}
```
What do you think?

**Comment by seyhangul** [comment]
Works great!
