### ISSUE TITLE
Floating-point truncation with `E` format

### ISSUE THREAD

**Issue by milancurcic** [jacobwilliams/json-fortran#230]
Hi Jacob et al.,

I noticed that I lose precision with some numbers in default (`E`) format. See example below:

``` fortran
program test_json
use iso_fortran_env,only:real64
use json_module,only:json_core,json_value,json_file

implicit none

type(json_core) :: json
type(json_file) :: jfile
type(json_value),pointer :: ptr

logical :: found
real(kind=real64),dimension(:),allocatable :: array1,array2

array1 = sqrt([2._real64,3._real64,7._real64])

! write array1 into file
call json % initialize(real_format='E')
call json % create_object(ptr,'')
call json % add(ptr,'value',array1)
call json % print(ptr,'test.json')
call json % destroy(ptr)

! read array2 from file
call jfile % initialize()
call jfile % load_file('test.json')
call jfile % get('value',array2,found)
call jfile % destroy()

! Compare
write(*,*)array1 == array2
write(*,*)array1
write(*,*)array2

endprogram test_json
```

The output is (gfortran-6.2.0):

```
 F F F
   1.4142135623730951        1.7320508075688772        2.6457513110645907     
   1.4142135623730949        1.7320508075688770        2.6457513110645912   
```

The truncation happens because 18 (including comma) digits are used in the format, but the leftmost significand digit is always zero, so you effectively store 16 meaningful digits:

```
$ cat test.json 
{
  "value": [
    0.1414213562373095E+1,
    0.1732050807568877E+1,
    0.2645751311064591E+1
  ]
}
```

If I use `real_format='EN'` or `real_format='ES'` when initializing, precision is maintained and my comparison test passes. 

I think the `E` behavior can be fixed by using an extra significand digit when setting the format in `src/json_value_module.F90`.

[This issue](https://github.com/jacobwilliams/json-fortran/issues/39) discusses parts of the implementation.

**Comment by jacobwilliams** [comment]
Thanks for reporting this. I'll take a look.

**Comment by zbeekman** [comment]
This smells like a bug I may have introduced... or at least a corner case I missed... let me know if you need help.

**Comment by szaghi** [comment]
@zbeekman Are you thinking to `compact_real`? The saved json file seems good (compacted well), the garbage seems to be present only in the result of `get`, or am I missing something? I am using your compacting procedure quite intensively and such a garbage has not been observed.

 I never used the format initialization with json-fortran, @jacobwilliams can you tell me this option affects only the *output methods* (like print and get ones) or also the internal storage (but I think you use for this a real real and not a string)? Is it possible that `print` and `get` use different formats/compactor?

Cheers.

**Comment by milancurcic** [comment]
@szaghi Notice that the saved json file truncates (rounds) the rightmost digit (compare with `array1`). The garbage in `array2` that you mention happens because `array2` is being read from a truncated file. Floating-point numbers should be exactly reproducible if provided enough digits in the string.

**Comment by szaghi** [comment]
@milancurcic Ops... I have to buy a bigger smartphone :smile: I did not recognize that array2 is load by the same file of load... Now I see also the rounding into file (I was not able to count the digits). So simply the file is save badly?

**Comment by jacobwilliams** [comment]
@zbeekman I incremented `rp_addl_safety` by one. It seems to work for various values, but I don't really have any "science" to back it up.

**Comment by zbeekman** [comment]
I'm on my way back from the overset grid symposium at Paine field in Everett and will try to look at the "science" of this as soon as I get a chance.

**Comment by milancurcic** [comment]
@jacobwilliams @zbeekman I think this fix should resolve all cases. The original code was storing 16 digits when using `E` format, however preserving doubles require at least 17, see [here](https://en.wikipedia.org/wiki/Double-precision_floating-point_format#IEEE_754_double-precision_binary_floating-point_format:_binary64).

**Comment by zbeekman** [comment]
@milancurcic I agree but just wanted to look at the logic again to convince myself and understand the problem.

**Comment by zbeekman** [comment]
As long as we're trimming any trailing blank space I give this fix my approval...

**Comment by jacobwilliams** [comment]
Agree.  

@milancurcic Thanks for reporting this! I've been saving real numbers with 16 digits for years...I think I'm going to have to make some changes to some other codes.
