### ISSUE TITLE
Specify default real and integer kinds

### ISSUE THREAD

**Issue by jacobwilliams** [jacobwilliams/json-fortran#238]
Add option to specify the default real and integer kinds via a compiler directive. See original discussion at #236.

Suggestion:
```fortran
#ifdef REAL32
    integer,parameter,public :: RK = real32   !! Default real kind [4 bytes]
#elseif REAL64
    integer,parameter,public :: RK = real64   !! Default real kind [8 bytes]
#elseif REAL128
    integer,parameter,public :: RK = real128  !! Default real kind [16 bytes]
#else
    integer,parameter,public :: RK = real64   !! Default real kind if not specified [8 bytes]
#endif

#ifdef INT8
    integer,parameter,public :: IK = int8      !! Default integer kind [1 byte]
#elseif INT16
    integer,parameter,public :: IK = int16     !! Default integer kind [2 bytes]
#elseif INT32
    integer,parameter,public :: IK = int32     !! Default integer kind [4 bytes]
#elseif INT64
    integer,parameter,public :: IK = int64     !! Default integer kind [8 bytes]
#else
    integer,parameter,public :: IK = int32     !! Default integer kind if not specified [4 bytes]
#endif
```

With maybe some introspection in the build system to warn if a requested kind doesn't exist.

**Comment by milancurcic** [comment]
@jacobwilliams @zbeekman Sorry to resurrect this, today I tried building (from master) with cmake and couldn't find any cmake rules to specify real precision at configure time. What worked for me was the following in `json-fortran/cmake/pickFortranCompilerFlags.cmake`:

```
  if ( REAL )
    message ( STATUS "Configuring build for ${REAL}-bit reals" )
    add_definitions ( -DREAL${REAL} )
  endif ()

  if ( INT )
    message ( STATUS "Configuring build for ${INT}-bit integers" )
    add_definitions ( -DINT${INT} )
  endif ()
```
Then I just do `FC=gfortran cmake .. -DREAL=32` to build single precision library, for example.

Let me know if this is desirable and I will make a pull request.

**Comment by jacobwilliams** [comment]
I'm not a big CMake user, so I can't say if this is the proper way to do it. But if it works, then I guess it's OK with me.

**Comment by zbeekman** [comment]
@milancurcic Looks OK to me, but don't you need `cmake .. -DREAL=REAL32`? I think you should setup integer and real kinds via a cache variable with the STRING type: https://cmake.org/cmake/help/latest/command/set.html#set-cache-entry and then set the `STRINGS` property on the cache variable so you can get a drop down list. https://cmake.org/cmake/help/latest/prop_cache/STRINGS.html#prop_cache:STRINGS

**Comment by zbeekman** [comment]
I can do this too... doesn't look like much work. Sorry I haven't gotten to it sooner.

**Comment by milancurcic** [comment]
@zbeekman Thank you! My original suggestion works as is, i.e. if you pass `-DREAL=32` to cmake, tne defined macro becomes `-DREAL32`, see the `add_dedinitions` line. If there is a more cmakeish way to do it, please do. 

Another thing I think this should do is check if the passed value for REAL or INT is one of valid options, and throw an error otherwise.

**Comment by zbeekman** [comment]
> My original suggestion works as is, i.e. if you pass -DREAL=32 to cmake, tne defined macro becomes -DREAL32, see the add_dedinitions line. If there is a more cmakeish way to do it, please do.

Ah, my bad, I read it too quickly. Of course it works because you probably copy-pasted it from your own use! Duh...

> Another thing I think this should do is check if the passed value for REAL or INT is one of valid options, and throw an error otherwise.

Yes setting the strings property is a step in the right direction for this; in `ccmake` or `cmake-gui` a drop-down menu will appear with the valid entries. I agree that we should complain if the user passes something weird.
