### ISSUE TITLE
variable length allocatable string array

### ISSUE THREAD

**Issue by jacopo-chevallard** [jacobwilliams/json-fortran#245]
Hi, I have a question for allocatable string arrays:

To read a (scalar) string from a JSON structure I **must** use a variable length string, as in:

```fortran
use json_module, only : json_file
use json_kinds, only: json_CK  => CK

character(kind=json_CK, len=:), allocatable :: string
character(kind=json_CK, len=:), allocatable :: string_scalar
type(json_file) :: json

string = '{"string_scalar":"x"}'
call json%get("string_scalar", string_scalar)
```

while if I try to read an array of string by using a variable length (allocatable) string, as in,
```fortran
use json_module, only : json_file
use json_kinds, only: json_CK  => CK

character(kind=json_CK, len=:), allocatable :: string
character(kind=json_CK, len=:), allocatable :: string_array(:)
type(json_file) :: json

string = '{"string_array":["x", "y", "z"]}'
call json%get("string_array", string_array)
```

I get the compiler error (using ``gcc version 6.2.0``):
```
call json%get("string_array", string_array)
               1
Error: Found no matching specific binding for the call to the GENERIC 'get' at (1)
```

While using a fixed length allocatable string, as in, 
```fortran
use json_module, only : json_file
use json_kinds, only: json_CK  => CK

character(kind=json_CK, len=:), allocatable :: string
character(kind=json_CK, len=1), allocatable :: string_array(:)
type(json_file) :: json

string = '{"string_array":["x", "y", "z"]}'
call json%get("string_array", string_array)
```
does the job.

Is the different usage of fixed/variable length strings for reading scalar/array strings from JSON due to the current compiler support of variable length strings?

**Comment by szaghi** [comment]
@jacopo-chevallard 

The error you reported means that the generic `get` has not a binding with a *string array* output with deferred length. Your last test uses a fixed length, that indeed makes sense. Consider the following example:

```fortran
program test_string
  implicit none
  character(len=:), allocatable :: array(:)

  allocate(array(1:2))

endprogram test_string  
```

If you try to compile it with both Intel or GNU compiler you obtain:

```shell
→ ifort -check -warn -debug -std08 test.f90
test.f90(6): error #8232: If any object being allocated in the ALLOCATE statement has deferred type parameter, either type specification or SOURCE= or MOLD= specifiers shall appear.   [ARRAY]
  allocate(array(1:2))
-----------^
compilation aborted for test.f90 (code 1)

# or

→ gfortran -C -g test.f90
test.f90:6:11:

   allocate(array(1:2))
           1
Error: Allocate-object at (1) with a deferred type parameter requires either a type-spec or SOURCE tag or a MOLD tag
```

This make sens: if you try to allocate an array of deferred length strings you should provide their length (that must be same for all elements of the array). The allocate step is necessary for the `get` method (automatic LHS allocation or explicit one).

So, if Jacob implement a binding with deferred length he must make a choice: how long will be the length of each element? Probably, the only possibility is to count the maximum length of all elements in the JSON array and allocate the array string with something like

```fortran
allocate(string_array(elements_number), mold=repeat('', max_length))
! fill the string_array
```

This could be helpful for the cases where the elements length is unknown *a priori*, but it has the overhead to compute the maximum length. In the case you know *a priori* the length, your array of explicit length  strings is better (faster). 

In any case, I do not think this is a problem of *compiler support*: IO can be done only with allocated strings.

Cheers

**Comment by jacopo-chevallard** [comment]
@szaghi sorry, I wasn't probably clear enough: my point was about consistency about the use of variable length strings in the case of scalar/array entries.

I'm aware that you need a "special" way to allocate a variable length Fortran string array, as the one you suggest, or simply
```fortran
allocate(character(max_length) :: str(elements_number))
```
and this requires determining ``max_length`` by counting the length of each element in the string array. From my perspective, consistency in the API for parsing JSON structures is more important than performance, but I'm sure we all have different opinions on this (ideally one could allow both cases within the same generic interface, but I'm not sure this would work).

**Comment by szaghi** [comment]
yes, I think so, I agree with you. My point was only to highlight that probably Jacob has not implemented it not for a problematic compiler support rather to avoid to make an *a priori* choice. While for a scalar-get the length is unique, for an array-get it is not (each element could have their own different length). I agree that we can have both. Another option could be to accept an array of *string* class where now each element could have its own different length... but this is another (esoteric) option.

Cheers

**Comment by jacobwilliams** [comment]
Yes, I admit the current inconsistency is non-ideal. I would have liked to have an allocatable array of allocatable strings (that can each be different lengths), but that is not allowed (I didn't want to force user to have to use some varying string implementation). So I think I just made the choice to use a fixed length string.

I could add a variable length option, where it gets the max length of all the strings. (yes, there would be a performance penalty, it would have to go through the array twice). But the user might be OK with that. 

Is it possible to have a generic interface where one has a `character(len=*)`, and another has a `character(len=:),allocatable`? I thought I tried that one time and it didn't work? I'll try it out later today and see.

**Comment by jacopo-chevallard** [comment]
> Is it possible to have a generic interface where one has a ``character(len=*)``, and another has a ``character(len=:),allocatable``? I thought I tried that one time and it didn't work? I'll try it out later today and see.

I would say no, but worth trying

**Comment by jacobwilliams** [comment]
Notes: 
* If I can't do the generic interface mentioned above, perhaps modify the arguments somewhat for the allocatable version? Maybe also return an integer array with the actual lengths of each element? Would that be useful?
* Another option that works now is, if you do want to use your own varying string implementation, you can populate each element using `json_get_array` with a callback function. Provide an example showing how to do this.

**Comment by jacobwilliams** [comment]
See `get_alloc_string` branch. Work in progress...

**Comment by jacobwilliams** [comment]
Note: it doesn't seem to work for gfortran 4.9 or 5 (compiles, but then crashed when I try to allocate the array). So, this will return 6 or later.

**Comment by jacobwilliams** [comment]
My solution is this:

```fortran
program test

use json_module, only : json_file
use json_kinds, only: json_CK  => CK

implicit none

character(kind=json_CK,len=:), allocatable :: string
character(kind=json_CK,len=:),dimension(:),allocatable :: string_array
integer,dimension(:),allocatable :: ilen
type(json_file) :: json
integer :: i

string = '{"string_array":["x", "y ", "z  "]}'
call json%load_from_string(string)
call json%get('string_array', string_array, ilen=ilen)

do i=1,3
    write(*,*) ilen(i), '-->'//string_array(i)//'<--'
end do

end program test
```
Results:
```
           1 -->x  <--
           2 -->y  <--
           3 -->z  <--
```
So, the string length is the size of the largest one, and you also get the actual length of each one in the `ilen` array. What do you think? It would be nice to have the `ilen` array be optional, but then the compiler couldn't distinguish between this one and the `character(len=*)` one.

**Comment by jacopo-chevallard** [comment]
I think that this is the best that we can get, you can either change the method name, or the interface has to be different... and I think that the option you adopted is the best one!
