### ISSUE TITLE
Stop using github to do tagging, use command line

### ISSUE THREAD

**Issue by zbeekman** [jacobwilliams/json-fortran#246]
```
$ git describe
1.0.0-497-g74b5c2b
$ git branch
* master
$ git pull origin master
From git://github.com/jacobwilliams/json-fortran
 * branch            master     -> FETCH_HEAD
Already up-to-date.
$ git remote -v
origin	git://github.com/jacobwilliams/json-fortran.git (fetch)
origin	git://github.com/jacobwilliams/json-fortran.git (push)
```

'nuff said, lol

(To clarify: I don't know exactly why, but using github to tag a project means that the tag doesn't show up when you `git describe` the project. I find this annoying. Tagging from the command line makes `git describe` work as expected, showing you how many commits from the last tag you are and the tag and your current SHA)

**Comment by zbeekman** [comment]
Also to clarify, this is just a suggestion, sorry for being flippant :-)

**Comment by jacobwilliams** [comment]
Interesting. I think the tag gets generated when I draft a new release via the web interface? (I don't recall if I add tags in any other way... if I did it would be via SourceTree since I don't use the git command line :) ). I do see all the different version tags in SourceTree, so I wonder why git-describe doesn't seem to recognize them?

**Comment by milancurcic** [comment]
> I think the tag gets generated when I draft a new release via the web interface? (I don't recall if I add tags in any other way

Correct. Release is a Github concept that also creates a git tag. Otherwise tags can be made using `git tag`, similarly to `git branch`.

**Comment by zbeekman** [comment]
Yes generating a release will generate a tag, unless you attach it to a
pre-existing one. So my recommendation is tag in source-tree, first, push
the tag to github, then create the release, pointing it to the tag.

The command line sees the tags too... it just doesn't know that master is
actually 5.y.z-<n-commits>-<SHA> it thinks master is 1.0.0-BIGNUMBER-SHA.
The SHA will always be right, but master doesn't know it is only a few
commits beyond the last tag/release.  I'm guessing 1.0.0 was tagged in
source-tree or on the command line.

On Fri, Dec 16, 2016 at 12:12 PM Jacob Williams <notifications@github.com>
wrote:

Interesting. I think the tag gets generated when I draft a new release via
the web interface? (I don't recall if I add tags in any other way... if I
did it would be via SourceTree since I don't use the git command line :) ).
I do see all the different version tags in SourceTree, so I wonder why
git-describe doesn't seem to recognize them?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jacobwilliams/json-fortran/issues/246#issuecomment-267644340>,
or mute the thread

**Comment by jacobwilliams** [comment]
OK, I can do what you suggest starting with the next release. Lets leave this open as a reminder to me.

(Maybe I did tag 1.0 with sourcetree...I don't recall).

**Comment by zbeekman** [comment]
> Correct. Release is a Github concept that also creates a git tag. Otherwise tags can be made using git tag, similar to git branch.

Also, to clarify, you can use a pre-existing tag in a release (so a funky new one is not created)

**Comment by jacobwilliams** [comment]
Note to self: should update the Release Checklist document to include this.

**Comment by jacobwilliams** [comment]
FYI: I made the [5.2.0](https://github.com/jacobwilliams/json-fortran/releases/tag/5.2.0) tag in SourceTree... did it end up non-funky?

**Comment by zbeekman** [comment]
yup, worked like a charm

**Comment by zbeekman** [comment]
dang, @ilovezfs beat me to the Homebrew version bump PR
