### ISSUE TITLE
Question about compilation with libs

### ISSUE THREAD

**Issue by ytzhang0925** [jacobwilliams/json-fortran#248]
Hi author,

I am quite new to fortran compiler usage, so your patience is appreciated.

gcc 6.3.0 along with gfortran is installed on my VPS machine, and it seems that I successfully compiled your code and generated the libraries. My source code is in the folder `json-fortran-5.1.0` under my $HOME directory and I built your code in the directory `json-fortran-5.1.0-build`. The files under `json-fortran-5.1.0-build/lib` should be the libraries, I guess,` libjsonfortran.a  libjsonfortran.so  libjsonfortran.so.5.1  libjsonfortran.so.5.1.0`. But when I try to compile your `example1` code in the wiki page I got errors. 

I copied your example1 code into file example1.f90 under `lib`:

```
[root@vultr lib]# gfortran example1.f90 -L. -llibjsonfortran.so
example1.f90:3:12:

         use json_module
            1
Fatal Error: Can't open module file ‘json_module.mod’ for reading at (1): No such file or directory
compilation terminated.
```

Then I tried to put file `example1.f90` to the upper folder where the file json_module.mod lies. However, I got another error.

```
[root@vultr json-fortran-5.1.0-build]# gfortran example1.f90
/tmp/cc3vt2cU.o: In function `MAIN__':
example1.f90:(.text+0x188): undefined reference to `__json_file_module_MOD___vtab_json_file_module_Json_file'
example1.f90:(.text+0x1c3): undefined reference to `__json_file_module_MOD_initialize_json_core_in_file'
example1.f90:(.text+0x1cf): undefined reference to `__json_file_module_MOD___vtab_json_file_module_Json_file'
example1.f90:(.text+0x1f2): undefined reference to `__json_file_module_MOD_json_file_load'
example1.f90:(.text+0x1fa): undefined reference to `__json_file_module_MOD___vtab_json_file_module_Json_file'
example1.f90:(.text+0x20e): undefined reference to `__json_file_module_MOD_json_file_print_to_console'
example1.f90:(.text+0x216): undefined reference to `__json_file_module_MOD___vtab_json_file_module_Json_file'
example1.f90:(.text+0x23d): undefined reference to `__json_file_module_MOD_json_file_get_integer'
example1.f90:(.text+0x259): undefined reference to `__json_file_module_MOD___vtab_json_file_module_Json_file'
example1.f90:(.text+0x280): undefined reference to `__json_file_module_MOD_json_file_get_integer'
example1.f90:(.text+0x29c): undefined reference to `__json_file_module_MOD___vtab_json_file_module_Json_file'
example1.f90:(.text+0x2c3): undefined reference to `__json_file_module_MOD_json_file_get_integer'
example1.f90:(.text+0x2df): undefined reference to `__json_file_module_MOD___vtab_json_file_module_Json_file'
example1.f90:(.text+0x2f8): undefined reference to `__json_file_module_MOD_json_file_destroy'
example1.f90:(.text+0x303): undefined reference to `__json_file_module_MOD___vtab_json_file_module_Json_file'
example1.f90:(.text+0x31d): undefined reference to `__json_file_module_MOD_json_file_failed'
collect2: error: ld returned 1 exit status
```

I am not sure whether this problem is due to any problems during cmake or gfortran compilation grammar. Could you please tell me the solution?

Regards, 
Yuanting

**Comment by zbeekman** [comment]
Hi Yuanting,

If you use the CMake build system, I believe the `make install` command should put the libraries and the mod files where the compiler will look by default... I don't recall if the bash build script will also put them in default locations.

I am not the primary author/maintainer, just a humble contributor, but I notice two things:

 1. The convention when specifying a library to link against is that the leading `-l` is short hand for `-lib` so having `-llib...` means the linker is looking for `liblib...`.
 2. I'm not an expert on shared objects vs static libraries, but I think normally you leave the library extension off of the library specified with the `-l` flag. So the correct usage, I think is: `-ljsonfortran`
 3. You need to use the `-L` flag to tell the linker where to find the libraries. So I think it should, in your case, be: `-L${HOME}/json-fortran-5.1.0-build/lib`
 4. The compiler can't find the module file, unless you help tell it where to look. There is often a special module path flag for Fortran compilers, I think it's `-J` for GFortran, but often they also look in the directory specified with `-L` and `-I`. I typically just use `-I` and install module files into `<prefix>/include` but people also put them in `<prefix>/lib` sometimes or in custom module directories (my least favorite of the options).

Also, N.B., `.mod` files are never portable across compiler vendors, and often they are not portable between releases from the same vendor.

Hope this helps.

**Comment by ytzhang0925** [comment]
Hi zbeekman,

Thanks for your help and finally I managed to run the example1.f90 successfully!

Still, I encountered a problem when running the program.

I compiled the f90 file using:

`gfortran example1.f90 -L${HOME}/json-fortran-5.1.0-build/lib -ljsonfortran -I${HOME}/json-fortran-5.1.0-build/include`

and everything seemed to be OK.

However, when I tried to execute `a.out`, the following texts returned:

`./a.out: error while loading shared libraries: `libjsonfortran.so.5.1`: cannot open shared object file: No such file or directory`

Obviously `a.out` is trying to find the library `libjsonfortran.so.5.1`. Then I found the lib exists as a link to `libjsonfortran.so.5.1.0`

```
[root@vultr lib]# ll
total 328
-rwxr-xr-x. 1 root root  13451 Jan 25 07:47 a.out
-rw-r--r--. 1 root root    874 Jan 24 06:48 example1.f90
-rw-r--r--. 1 root root 172492 Jan 24 03:12 libjsonfortran.a
lrwxrwxrwx. 1 root root     23 Jan 25 01:04 libjsonfortran.so -> libjsonfortran.so.5.1.0
lrwxrwxrwx. 1 root root     23 Jan 24 03:12 libjsonfortran.so.5.1 -> libjsonfortran.so.5.1.0
-rwxr-xr-x. 1 root root 136505 Jan 24 03:12 libjsonfortran.so.5.1.0
```

The link seemed to be invalid for the f90 program. So I removed the link `libjsonfortran.so.5.1` and renamed `libjsonfortran.so.5.1.0` as `libjsonfortran.so.5.1`, then recompiled the fortran program, exexute `a.out`. The f90 program run successfully.

I do not understand why the link is invalid for use.

Regards,
Yuanting

**Comment by zbeekman** [comment]
@ytzhang0925 Are you on Linux or MacOS? Also, if you don't change the symbolic link, can you please recompile a.out and then run `ldd a.out` on Linux or `libtool -L a.out` on MacOS? That will show any unresolved dynamic libraries. If you want to avoid the headache of dynamic libraries, you can just pass libjsonfortran.a directly when linking:

```
gfortran example1.f90 /path/to/libjsonfortran.a -I /path/to/include/dir/with/jsonfortran/modules -o example1
```

If you have any further questions please let us know otherwise, can this issue be closed?

**Comment by zbeekman** [comment]
I move to close this issue as resolved unless @ytzhang0925 objects.

**Comment by m4r35n357** [comment]
I have also attempted to use this lobrary, but after building successfully there seems to be no guidance on how to invoke the library (in my case via gfortran).

I have tried using:
`export LD_LIBRARY_PATH=/opt/JSON-Fortran/json-fortran/lib:.`
and
`gfortran -Wall -O2 -fimplicit-none Json.f90 -I/opt/JSON-Fortran/json-fortran/lib`
with the result:
```
/tmp/ccb9N8iZ.o: In function `MAIN__':
Json.f90:(.text+0x121): undefined reference to `__json_file_module_MOD___vtab_json_file_module_Json_file'
Json.f90:(.text+0x1d2): undefined reference to `__json_file_module_MOD_initialize_json_core_in_file'
Json.f90:(.text+0x1de): undefined reference to `__json_file_module_MOD___vtab_json_file_module_Json_file'
Json.f90:(.text+0x204): undefined reference to `__json_file_module_MOD_json_file_load'
Json.f90:(.text+0x212): undefined reference to `__json_file_module_MOD___vtab_json_file_module_Json_file'
Json.f90:(.text+0x220): undefined reference to `__json_file_module_MOD_json_file_print_to_console'
Json.f90:(.text+0x241): undefined reference to `__json_file_module_MOD___vtab_json_file_module_Json_file'
Json.f90:(.text+0x24f): undefined reference to `__json_file_module_MOD_json_file_get_integer'
Json.f90:(.text+0x27b): undefined reference to `__json_file_module_MOD___vtab_json_file_module_Json_file'
Json.f90:(.text+0x289): undefined reference to `__json_file_module_MOD_json_file_get_integer'
Json.f90:(.text+0x2b1): undefined reference to `__json_file_module_MOD___vtab_json_file_module_Json_file'
Json.f90:(.text+0x2bf): undefined reference to `__json_file_module_MOD_json_file_get_integer'
Json.f90:(.text+0x2d6): undefined reference to `__json_file_module_MOD___vtab_json_file_module_Json_file'
Json.f90:(.text+0x2e4): undefined reference to `__json_file_module_MOD_json_file_destroy'
Json.f90:(.text+0x2f2): undefined reference to `__json_file_module_MOD___vtab_json_file_module_Json_file'
Json.f90:(.text+0x300): undefined reference to `__json_file_module_MOD_json_file_failed'
collect2: error: ld returned 1 exit status

```

**Comment by m4r35n357** [comment]
Apologies, your very last comment solved my problem.  Would you consider adding it to the README?

Anyway, thanks and apologies for the hijacking - this issue thread seems to be the only place on the internet where this is being discussed ;)

**Comment by zbeekman** [comment]
@m4r35n357  What exactly do you mean by "guidance on how to actually invoke the library"?

> I have also attempted to use this library, but after building successfully there seems to be no guidance on how to actually invoke the library (in my case via gfortran).

Also, can you please clarify exactly what information you feel is missing in the README? We want to do our best to support users of diverse backgrounds and skill sets, but right now, it's not really clear to me what precise issue needs to be remedied other than basic understanding of linking . executables with libraries... which is completely valid btw, this stuff used to confuse me too--but is more fundamental and not specific to JSON-Fortran.

If you are referring to the topic of linking against the library after you've built and installed it, then we may consider adding some additional instructions somewhere. This topic is fairly complex and varies from system to system and may even depend on where you installed the library.

The easiest thing to do is to link against the static library. (`.a` file extension on Linux, macOS and most other *nixes)

Now, if you installed JSON-Fortran into a "normal" location on one of these *nix systems you can just pass `-ljson-fortran` when linking your code. Depending on your system it may pick up the shared/dynamic version of the library, but if it was installed to a standard location, this should be OK because the dynamic linker (`ld`) will be looking in that system library anyway.

If you don't have admin permissions and JSON-Fortran is not available on your system, then the best easiest way to link against JSON-Fortran is to just pass the full path to the static library to the linker.

**Comment by m4r35n357** [comment]
It was just the build command that I couldn't work out, there are so many implementations and versions of Fortran that it is hard to search for stuff like that, and it is not covered well in gfortran docs.

Anyway I got it built (thanks), then got distracted, but about to try again (hope it works with 128-bit reals!)

**Comment by zbeekman** [comment]
@m4r35n357 What application do you need quad precision for, out of curiosity? I hope it's not computationally intensive, because you'll be moving 2x the data over doubles and have half the number of SIMD registers.

**Comment by megranaterogger** [comment]
my god, gfortran is totally bull of shit, every compolieing step were participate with errors
