### ISSUE TITLE
Question/RFE: support for RFC 6901: JSON Pointer

### ISSUE THREAD

**Issue by zbeekman** [jacobwilliams/json-fortran#249]
Hey Jacob,

I came across [RFC 6901: JSON pointer](https://tools.ietf.org/html/rfc6901) and was wondering if JSON-Fortran has support for this or would be interested in supporting this. i.e. I'm wondering if the current syntax for addressing elements follows this RFC 6901.... or what would need to happen to implement it. (See the example section)

**Comment by jacobwilliams** [comment]
We're not using it, but I like it. I think I can add it. Probably as an option to use the current way (which is inherited from `fson` and doesn't work if the keys contain special characters like `.` or `()`) or this way.

**Comment by jacobwilliams** [comment]
Note: I'd need to write an alternate version of `json_get_by_path` and perhaps also `json_get_path`.
