### ISSUE TITLE
build tools

### ISSUE THREAD

**Issue by bruceravel** [jacobwilliams/json-fortran#26]
Gentlemen,

In the project for which I am using json-fortran, I have chosen to use SCons as the build system.

I find that the `build.sh` file works just fine, but it's a little too simple for purposes.  I have no problem with CMake, but as written the CMake files for json-fortran have a requirement on jsonlint (there are many things called jsonlint, you seem to be using [this one](https://github.com/zaach/jsonlint), right?), which, in turn, requires that node.js be installed.  node.js is supercool, but not something I want to impose upon my users.

Here (https://gist.github.com/bruceravel/c74dd55c5a33a6966437) is the `SConstruct` file that I came up with.  It very closely emulates the behavior of the `build.sh` script, but with logic for dependencies, cleaning, and installing.

If you think that others might appreciate this, then you can drop it in the top directory under the name `SConstruct`.  With it in place (and with SCons installed), the library is built by typing `scons` and installed by `scons install` or `sudo scons install`.  I can also imply leave the gist in place for linking to.

If you would rather not have a proliferation of build tools in the repo, I completely understand.

Regardless, I am grateful for json-fortran.  It has really filled a need in my work. :smiley:

**Comment by zbeekman** [comment]
@bruceravel any pointers on how to modify the `SConstruct` file if the file `son_example.f90` was moved into `./src/tests` AND split into two files: `json_unit_tests.f90` a module holding all but the main executable from the former `son_example.f90` program file and then the program in `json_example.f90` `USE`s the new  module file for everything but the executable code? My Python is not so hot, and I know nothing of SCons.

**Comment by bruceravel** [comment]
@zbeekman : happy to help!

This patch fixes up SConstruct for the current HEAD of the master branch:

https://gist.github.com/bruceravel/174bff9ea6d92502d463

I don't understand the comment about `json_unit_tests.f90`.  There is no such file in `./src/` or `./tests` (and there is no such directory `.src/tests`) in the master branch.  And there are no other code branches.  So I don't know what you are asking me to do.

**Comment by bruceravel** [comment]
Aha!  I just saw #49.  When you finish that work, I'll be happy to update the SConstruct file to reflect it.

Cheers, B

**Comment by zbeekman** [comment]
Thanks @bruceravel… I’m a pretty quick study usually, so once I have my branch looking ready for a PR (dealing with #27 and #30) I may have you go take a look and update the SCons build… Seeing that update should get me started on being able to understand and update SConstruct on my own…
