### ISSUE TITLE
Function ‘json_failed’ at (1) has no IMPLICIT type

### ISSUE THREAD

**Issue by kheaactua** [jacobwilliams/json-fortran#260]
Going off the example on the [wiki](https://github.com/jacobwilliams/json-fortran/wiki), I get the error:

The code
```fortran
CALL config%load_file('test.json'); if (json_failed()) stop
```

Yields the build error:

```
gfortran    -ffree-line-length-none -Ijson-fortran/bld   -c calcComparisonStats.f90 -o calcComparisonStats.o
calcComparisonStats.f90:47:41:

  CALL config%load_file('test.json'); if (json_failed()) stop
                                         1
Error: Function ‘json_failed’ at (1) has no IMPLICIT type
```

If I remove `json_failed`, everything works, I can compile, read values, etc.  I'm only loading the `json_module` module.  I tried adding `use json_value_module, ONLY: json_failed`, but it still couldn't find it.  The symbol exists though,

```
nm json-fortran/bld/lib/libjsonfortran.so | grep json_failed
0000000000008a10 T __json_value_module_MOD_json_failed
```

I built off b1af52dfce1cd43279ca167e7645d80b6079b266 with `gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4)`.  Looking at the issues though, it seems everyone else can use this function without any problem.

**Comment by jacobwilliams** [comment]
Sorry, that was for an earlier version. The current syntax is:
```fortran
CALL config%load_file('test.json'); if (config%failed()) stop
```
Try that and it should work. I'll update the Wiki.

**Comment by kheaactua** [comment]
Worked perfectly!  Thanks!
