### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by jacobwilliams** [jacobwilliams/json-fortran#27]
Need some rigorous unit tests.

**Comment by zbeekman** [comment]
Close? Or to ask it differently, what needs to happen for this issue to be resolved?

**Comment by jacobwilliams** [comment]
Let's keep open. Now that there's a good system in place, I'm going to add some more unit test.

**Comment by zbeekman** [comment]
I put this comment regarding a better way to deal with stuff in the `files` directory in PR #73 but this might be a better place to discuss it, so I’m copying the relevant portion here:

>I’m wondering if we should have a convention to distinguish test inputs from test outputs. That way we can use file globbing to vacuum up the appropriate input files and make sure they’re copied to the build tree. At the same time if we had a convention for the test outputs, we could also automatically send them through jsonlint and compare the actual output with the anticipated output. What do you think of this idea?

**Comment by jacobwilliams** [comment]
Agreed.  Ideally, it should be completely automated.

**Comment by zbeekman** [comment]
I think we should either create subdirectories of the files directory named `inputs` where inputs go and `outputs` where the files that should match the outputs go. Then each test can read from `files/inputs/file.json` if it requires input, but write to `files/file.json` so that `files/file.json` can be compared with `files/ouputs/file.json` (Here “file.json” is just a stand in for whatever the actual file name is.) Thoughts?

**Comment by zbeekman** [comment]
I just added [a page to the wiki](https://github.com/jacobwilliams/json-fortran/wiki/List-of-un-exercised-code) to track the procedures that aren’t called in any of the unit tests. Ideally, tests will be added in the future to address all issues there, and the wiki updated, to reflect the progress.

**Comment by jacobwilliams** [comment]
Agree.  One thing that shouldn't happen (that currently does), is files committed in the repo shouldn't be overwritten in place by the unit tests.  That seems like bad practice.  The "truth" files should be in one dir, and the unit test outputs generated in another, then compared. 
 
Great idea for the wiki.  Definitely will work on getting all these routines tested.

**Comment by zbeekman** [comment]
I updated the page on the wiki with the output of the FoBiS.py gcov analyzer markdown. I manually edited some of it and moved things around, but I think we could get this to auto-deploy in the future if that interests you, the same way we auto-deploy the ROBODoc documentation. Then, we could have a slightly nicer coverage display page than the one coveralls uses, with he breakdown of covered and uncovered procedures.

Also, PR #86 address the issue wherein tests overwrite files committed to the repo.

**Comment by zbeekman** [comment]
Here is a link to the updated wiki page with the test coverage: https://github.com/jacobwilliams/json-fortran/wiki/Coverage-Analysis

**Comment by szaghi** [comment]
@jacobwilliams and @zbeekman 

The gcov analyzer in FoBiS.py is very *young*. If you want to use it, I can introduce any feature you want, e.g. for customizing the report *theme* and/or reports comments.

Let me know of any features you like.

See you soon.

**Comment by zbeekman** [comment]
One thing that would be nice is to make the uncovered procedures report come before the covered procedure report, since they are more important to test. Also I customized the colors for the pie charts (green = covered = good, red = uncovered = bad!) but in general I think the output is great as is.

**Comment by szaghi** [comment]
Tomorrow, I will try to push a new version with customizable colors and with inverted order of covered/uncovered.

See you soon.

**Comment by zbeekman** [comment]
@jacobwilliams I’m wondering if we should close this given the decent test coverage we’re getting… we could always open a new issue regarding improving test coverage to some target, but having an issue that’s just “unit tests” makes it seem like there aren’t any and that the project doesn’t have good QA measures.

**Comment by jacobwilliams** [comment]
Fair enough. Yes, we can continue to add to them.
