### ISSUE TITLE
Doc deployment broke?

### ISSUE THREAD

**Issue by jacobwilliams** [jacobwilliams/json-fortran#279]
It didn't seem to work for the 5.3.0 release.

**Comment by jacobwilliams** [comment]
Weird. It looks like the 5.3.0 docs were generated in [their folder](http://jacobwilliams.github.io/json-fortran/5.3.0/index.html), but none of the top level pages were updated (e.g. [here](http://jacobwilliams.github.io/json-fortran/page/releases/index.html)). It's always worked before, has something changed on Travis?

**Comment by jacobwilliams** [comment]
I think I fixed it. The issue may have been because I pushed the changes (updated `.VERSION` file, etc.) and the `5.3.0` tag at the same time? I removed the tag, pushed a minor change, and then pushed the tag again. Then it all worked.

**Comment by zbeekman** [comment]
huh strange... let me know if you run into this again and want me to look
