### ISSUE TITLE
HOW TO: read unknown length array of objects

### ISSUE THREAD

**Issue by andreafdaf** [jacobwilliams/json-fortran#282]
Hello, sorry to bother you again but it's really hard to read/understand the docs and find out how to do some more complex operations.

There is already an issue that points out how to create an array of objects (https://github.com/jacobwilliams/json-fortran/issues/92) but I cannot find out how to read an array of objects. For example:
```fortran
program test
  use json_module
  implicit none

  type(json_file) :: json
  integer :: vals(3)
  logical :: found

  call json%load_from_string('{ "a": [{"value": 1}, {"value": 2}, {"value": 3}]}')
  call json%print_file()

  call json%get("a[0].value", vals(1), found)
  call json%get("a[1].value", vals(2), found)
  call json%get("a[2].value", vals(3), found)

  print *, vals(:)

end program test
```

Here I can read the values because I already know that the array is 3 elements long, with a small problem: JSON arrays should have 0-based indexing, while this library reads them using 1-based indexing with index 0 being equal to index 1 (not a big issue though)

The real issue is: if I had a random number of elements in that array, how to read them? I did something like the following but it doesn't look like a good solution to me, is there a simpler/cleaner way?
```fortran
program test
  use json_module
  implicit none

  type(json_file) :: json
  integer, allocatable :: vals(:)
  character(32) :: arrayLengthString
  character(32) :: iString
  integer :: arrayLength = 1
  logical :: found
  integer :: tempVal
  integer :: i

  call json%load_from_string('{ "a": [{"value": 1}, {"value": 2}, {"value": 3}]}')
  call json%print_file()

  write(arrayLengthString, *) arrayLength
  call json%get("a[" // trim(arrayLengthString) // "].value", tempVal, found)
  do while (found)
    arrayLength = arrayLength + 1
    write(arrayLengthString, *) arrayLength
    call json%get("a[" // trim(arrayLengthString) // "].value", tempVal, found)
  end do

  allocate(vals(arrayLength - 1))

  do i = 1, size(vals)
    write(iString, *) i
    call json%get("a[" // trim(iString) // "].value", vals(i), found)
  end do

  print *, vals(:)
  
end program test
```

Thanks so much for your help so far :v:

**Comment by jacobwilliams** [comment]
You can use the `json_file.info()` method to inquire about variables (what kind they are, how many elements, etc). So something like this:
```fortran
    integer(json_ik) :: n_elements
    call json%info('a',n_children=n_elements)
    allocate(vals(n_elements))
    do i = 1, n_elements
        ! etc.
    end do
```
If you are OK with using pointers, you can also get the elements without having to create the strings (get a `json_value` pointer to `a` and then use `json_core.get_child()` to get the ith child).

As for the 1-based indexing, we are using Fortran after all. :)

**Comment by andreafdaf** [comment]
Wow, that's great! :smile: 

Apparently your library does a LOT more than it looks, it's a pity not having a proper documentation :cry: 

(touché for the index :wink:)

**Comment by jacobwilliams** [comment]
What we have is this:
* The source code documentation is here: http://jacobwilliams.github.io/json-fortran/ Every routine is documented, but I admit you do have to dig around to find what you want if you're just starting out.
* The wiki has a few very basic examples: https://github.com/jacobwilliams/json-fortran/wiki 
* You can also look at the various unit tests, which include a lot of examples of how to do stuff: https://github.com/jacobwilliams/json-fortran/tree/master/src/tests

But, yes, the documentation could be improved. Especially for beginners. I think all the info is there, but it needs to be better organized or something.
