### ISSUE TITLE
Intel project needs recursion flags

### ISSUE THREAD

**Issue by qolin1** [jacobwilliams/json-fortran#291]
It is easy to wind up calling JSON_GET_ARRAY recursively. Using Intel Fortran under Windows, with the settings in the .vfproj file supplied in the visual_studio folder, this causes an error: the local "element" is nullified on exit. This leads to a null pointer reference in outer recursive calls.

The .vfproj file should contain the flags 'EnableRecursion="true"' and 'ReentrantCode="reentrancyThreaded"' to prevent this. From Developer Studio menus it is Properties > Configuration Properties > Fortran > Code Genration, "Enable Recursive Routines=yes" and "Generate Reentrant code=Threaded".

**Comment by jacobwilliams** [comment]
Can you provide an example showing the bug? We need to make sure gfortran has the same fix too. I wonder if we could just add the `recursive` attribute to the subroutine.
