### ISSUE TITLE
String slice out of bounds in lowercase_character()

### ISSUE THREAD

**Issue by robertrueger** [jacobwilliams/json-fortran#293]
I think I have found a problem in the lowercase_character() method in the json_string_utilities module. An ifort 17 debug build stops in the second line here:

```fortran
i = index(upper,c)
c_lower = merge(lower(i:i),c,i>0)
```

with the message "**forrtl: severe (408): fort: (5): Variable <unknown> has substring starting point 0 which is less than one**" if `c` is a character not found in `upper`. The returned index is then 0 which causes the run-time to bail out when `lower(0:0)` is passed into the merge intrinsic.

It's not a problem with a release build, since `merge` (probably) doesn't access the 0 element if `i==0`.

This of course fixes the problem:

```fortran
    if (i>0) then
       c_lower = lower(i:i)
    else
       c_lower = c
    endif
```

**Comment by zbeekman** [comment]
Yes that looks like a bug, because you deference `lower(0:0)` in the merge statement....

**Comment by jacobwilliams** [comment]
Yes, I think I was being too clever in this routine. I can commit the fix this evening.
