### ISSUE TITLE
Problems with newer gfortran version.

### ISSUE THREAD

**Issue by SolidTux** [jacobwilliams/json-fortran#297]
I have problems with GFortran version 7.2.1. I've put an example project on [Gitlab](https://gitlab.com/SolidTux/jsontest) which runs correctly with 6.4.1, but not 7.2.1.

**Comment by jacobwilliams** [comment]
I'll try to test it when I get a chance. At first glance, I don't see anything wrong with the code. Sometimes, the compiler just has a bug. What error message are you getting?

**Comment by SolidTux** [comment]
I don't get any error, only the keys are not found in the JSON. But you could be right with the browser bug as I have other problems where I get a 'End of file' error when writing to a file. But I can't reproduce it in a small program it only happens in the full program which I can't publish.

**Comment by jacobwilliams** [comment]
FYI: I just tested it with gfortran 7.2.0 (on MacOS, installed via Homebrew) and it also works fine.

**Comment by zbeekman** [comment]
@SolidTux this sounds like a regression in the development version of GFortran (7.2.1 is not a stable released version, correct? It will become 7.3, I believe.)
