### ISSUE TITLE
Running jf_test_25 failed on High Sierra

### ISSUE THREAD

**Issue by petrvokac** [jacobwilliams/json-fortran#298]
json-fortran-6.1.0
uname -a
Darwin pvmb.local 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64

gfortran -v
Using built-in specs.
COLLECT_GCC=gfortran
COLLECT_LTO_WRAPPER=/usr/local/gfortran/libexec/gcc/x86_64-apple-darwin14/5.1.0/lto-wrapper
Target: x86_64-apple-darwin14
Configured with: ../gcc-5.1.0/configure --prefix=/usr/local/gfortran --with-gmp=/Users/fx/devel/gcc/deps-static/x86_64 --enable-languages=c,c++,fortran,objc,obj-c++ --build=x86_64-apple-darwin14
Thread model: posix
gcc version 5.1.0 (GCC) 

running ./build.sh: 

Running jf_test_25

=================================
   TEST 25
=================================

parsing...

printing...
{
  "str_array": [
    "1",
    "22",
    "333",
    "55555"
  ]
}

getting data...

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x109416092
#1  0x1094153b0
#2  0x7fff5ca7af59
./build.sh: line 382: 80887 Segmentation fault: 11  "./${TEST}"

**Comment by jacobwilliams** [comment]
It's probably a compiler bug. I know this test doesn't work on gfortran 4.9 or 5 (see [here](https://github.com/jacobwilliams/json-fortran/pull/265/commits/bb8573fa16754ff92d491ea65a9fd2c93925fce7)). It does work with 6.3.0 and 7.1.0. It's only the routines to get an array of allocatable strings, so if you don't call that routine, you shouldn't have any problems.
