### ISSUE TITLE
Tests not passing with gcc5.3.1 and gcc6.3.1.

### ISSUE THREAD

**Issue by edu159** [jacobwilliams/json-fortran#299]
Hi! I am having a hard time compiling in CentOS6 with gcc5.3.1 and gcc6.3.1 (from devtoolset-4 and devtoolset-5 respectively) in both 5.1 and 6.1 versions of json-fortran. Those toolsets are a collection of software (https://www.softwarecollections.org/) compiled for RHEL/CentOS as they are used in high performance computing and lot of building is carried out in those platforms to be compatible with HPC(quite old gnu libc). Is this a known issue? Is there any file generated form the tests I can upload to clarify more the issue?

**Comment by jacobwilliams** [comment]
What errors are you seeing?

**Comment by edu159** [comment]
Compiling-wise none. The problem is when I compile and run all the tests and most of them fail. The output I get is limited (only if certain test has passed or not). Is there any way of getting the logs after doing 'make test' so I can paste it here?

**Comment by zbeekman** [comment]
Are you building with CMake? Or with FoBiS.py? There's a good chance I need to spend some time updating the CMake test infra, because I don't think @jacobwilliams uses it much.

**Comment by edu159** [comment]
It is cmake. Furthermore it is not only the tests which fail. My program segfaults with those versions of the compiler if I include calls to your libraries. I have not looked deep into this since for gcc4.9.* and 7.2.* it works both the tests and my software so there is a correlation there... which, as usual, does not mean causation but...

**Comment by jacobwilliams** [comment]
Note: I'm currently testing the latest version of the library on Travis CI (#414) with gfortran 6.5, 7.4, 8.3, and 9.1. All the tests pass. Do you still have this issue?

**Comment by jacobwilliams** [comment]
Going to close this.
