### ISSUE TITLE
Test jf_test_28.f90 not passing using ifort2016 on RHEL 6

### ISSUE THREAD

**Issue by libuda** [jacobwilliams/json-fortran#301]
Test case 28 is failing with segmentation violation on my system:
```

=================================
   TEST 28
=================================


Original:

[1, 2, 3, 4, 5]

Reversed:

[5, 4, 3, 2, 1]
           5           0
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
jf_test_28         00000000004A3A75  Unknown               Unknown  Unknown
jf_test_28         00000000004A1837  Unknown               Unknown  Unknown
jf_test_28         0000000000466282  Unknown               Unknown  Unknown
jf_test_28         00000000004660D6  Unknown               Unknown  Unknown
jf_test_28         0000000000415755  Unknown               Unknown  Unknown
jf_test_28         000000000041B26D  Unknown               Unknown  Unknown
libpthread.so.0    0000003C3440F7E0  Unknown               Unknown  Unknown
jf_test_28         000000000040CFC3  MAIN__                     76  jf_test_28.f90
jf_test_28         000000000040C4CE  Unknown               Unknown  Unknown
libc.so.6          0000003C3401ED1D  Unknown               Unknown  Unknown
jf_test_28         000000000040C3D9  Unknown               Unknown  Unknown

```
It is failing in line 76
```fortran
   if (all(ivec==ivec_value_reversed)) then
```
when all values of the arrays are compared. I added a debug print in the original test to output the size of **ivec** and __ivec_value_reversed__ and it reports **5** and **0** (see output above).  
So, obviously it looks like that **ivec_value_reversed** does not get properly allocated as a 1st guess.

Intel Fortran compiler:
```
> ifort2016 --version
ifort (IFORT) 16.0.0 20150815
Copyright (C) 1985-2015 Intel Corporation.  All rights reserved.
```
System:
```
> more /etc/motd 
_______________________________________________________________________________
HP ProLiant XL190r Gen9            GNU/Linux        Hardware Platform:   x86_64
Red Hat Enterprise WS 6.9                           Kernel: 2.6.32-696.13.2.el6
```
Is that a known issue of the Intel compiler? The same issue occurs also with Intel2013.

Regards, libuda

**Comment by jacobwilliams** [comment]
This test is using the "auto LHS reallocation" of allocatable variables. This is standard Fortran, but earlier versions of the Intel compiler required you to use a special flag to enable it I believe.

**Comment by libuda** [comment]
Thanks. The flag is '-assume realloc_lhs'. All tests are passing using this flag, 28 too.

**Comment by ohcfe** [comment]
note:
    ./build.sh --compiler intel --cflags '-assume realloc_lhs'

won't work, as the --cflags argument would also need all the other compiler flags, instead edit build.sh and add --assume reallloc_lhs to INTELCOMPILERFLAGS
