### ISSUE TITLE
Cannot find information about version of json-Fortran

### ISSUE THREAD

**Issue by libuda** [jacobwilliams/json-fortran#302]
For an automated deployment of json-fortran it would be useful to extract the version of actual distribution from within a file. I wasn't able to find such information in the sources. 

If it is not provided I may suggest to add a file VERSION in the root directory containing the version information such as 

> \> more VERSION  
6.1.0

What do you think?

**Comment by zbeekman** [comment]
See [`.VERSION`](https://github.com/jacobwilliams/json-fortran/blob/master/.VERSION)

**Comment by libuda** [comment]
Cool 🙂
I had to merge v5.0.2 and 6.1.0 manually and just didn't recognize the file. 
Thx
