### ISSUE TITLE
Zero-length character passed to length-1 character dummy of add_to_path

### ISSUE THREAD

**Issue by ThemosTsikas** [jacobwilliams/json-fortran#303]
The NAG Fortran Compiler (6.2) complained about this, I removed the optional argument from the call and all tests pass.

```
diff --git a/src/json_value_module.F90 b/src/json_value_module.F90
@@ -6767,7 +6767,7 @@
                         call integer_to_string(i,int_fmt,istr)
                         call add_to_path(start_array//single_quote//parent_name//&
                                          single_quote//end_array//&
-                                         start_array//trim(adjustl(istr))//end_array,CK_'')
+                                         start_array//trim(adjustl(istr))//end_array)
                     case(2_IK)
                         ! rfc6901
                         call integer_to_string(i-1,int_fmt,istr) ! 0-based index
@@ -6791,7 +6791,7 @@
                     select case(json%path_mode)
                     case(3_IK)
                         call add_to_path(start_array//single_quote//name//&
-                                         single_quote//end_array,CK_'')
+                                         single_quote//end_array)
                     case default
                         call add_to_path(name,path_sep)
                     end select
@@ -6811,7 +6811,7 @@
                 select case(json%path_mode)
                 case(3_IK)
                     call add_to_path(start_array//single_quote//name//&
-                                     single_quote//end_array,CK_'')
+                                     single_quote//end_array)
                 case default
                     call add_to_path(name,path_sep)
                 end select

```

**Comment by jacobwilliams** [comment]
Interesting. I think we need to keep it though...since it has to do with the alternate "bracket notation" path mode. Maybe I don't have a test for this?

I think the way to fix it is to change this line:
```fortran
character(kind=CK,len=1),intent(in),optional :: path_sep
```
to this:
```fortran
character(kind=CK,len=*),intent(in),optional :: path_sep
```
But I will verify that.

**Comment by ThemosTsikas** [comment]
Yes, that is good too.

**Comment by ThemosTsikas** [comment]
Hello,

If you have access to the NAG Fortran Compiler, can you try

make Fortran_FLAGS="-C=all -PIC -g -gline" jf_test_1 -B

in a nagfor_build directory? When I run jf_test_1 I see


=================================
   TEST 1
=================================


parsing file ../files/inputs/test1.json

printing the file...
{
  "version": {
    "major": 2,
    "minor": 2,
    "patch": 1,
    "string": "2.2.1",
    "svn": 7191
  },
  "files": [
    "..\\path\\to\\files\\file1.txt",
    "..\\path\\to\\files\\file2.txt",
    "..\\path\\to\\files\\file3.txt",
    "test \u2FA4 \uABCD \uABCD\uABCDtest",
    "   test  \\u \" blah\\\" test test",
    "..\\path\\to\\files\\"
  ],
  "a": {
    "b": 1
  },
  "escape": " \" \\ \/ \b \f \n \r \t ",
  "empty_array": [],
  "empty_object": {},
  "empty_string": "",
  "data": [
    {
      "number": 1,
      "tf1": true,
      "tf2": false,
      "empty": null,
      "name": "Horatio",
      "array": [
        "1",
        "2",
        "3"
      ]
    },
    {
      "number": 2,
      "integer": 33,
      "real": 0.23330000000000001E+3,
      "name": "Nelson"
    }
  ],
  "rfc6901 tests": {
    "foo": [
      "bar",
      "baz"
    ],
    "  ": 0,
    "a\/b": 1,
    "c%d": 2,
    "e^f": 3,
    "g|h": 4,
    "i\\j": 5,
    "k\"l": 6,
    " ": 7,
    "m~n": 8
  }
}

printing each variable [namelist style]

version%major = 2
version%minor = 2
version%patch = 1
version%string = 2.2.1
version%svn = 7191
files(1) = ..\\path\\to\\files\\file1.txt
files(2) = ..\\path\\to\\files\\file2.txt
files(3) = ..\\path\\to\\files\\file3.txt
files(4) = test \u2FA4 \uABCD \uABCD\uABCDtest
files(5) =    test  \\u \" blah\\\" test test
files(6) = ..\\path\\to\\files\\
a%b = 1
escape =  \" \\ \/ \b \f \n \r \t
empty_array = ()
empty_object = {}
empty_string =
data(1)%number = 1
data(1)%tf1 = true
data(1)%tf2 = false
data(1)%empty = null
data(1)%name = Horatio
data(1)%array(1) = 1
data(1)%array(2) = 2
data(1)%array(3) = 3
data(2)%number = 2
data(2)%integer = 33
data(2)%real = 2.3330000000000001E+2
data(2)%name = Nelson
rfc6901 tests%foo(1) = bar
rfc6901 tests%foo(2) = baz
rfc6901 tests%   = 0
rfc6901 tests%a/b = 1
rfc6901 tests%c%d = 2
rfc6901 tests%e^f = 3
rfc6901 tests%g|h = 4
rfc6901 tests%i\j = 5
rfc6901 tests%k"l = 6
rfc6901 tests%  = 7
rfc6901 tests%m~n = 8

printing each variable [JSON style]

version.major = 2
version.minor = 2
version.patch = 1
version.string = 2.2.1
version.svn = 7191
files[1] = ..\path\to\files\file1.txt
files[2] = ..\path\to\files\file2.txt
files[3] = ..\path\to\files\file3.txt
files[4] = test \u2FA4 \uABCD \uABCD\uABCDtest
files[5] =    test  \u " blah\" test test
files[6] = ..\path\to\files\
a.b = 1
escape =  " \ /


empty_array = ()
empty_object = {}
empty_string =
data[1].number = 1
data[1].tf1 = true
data[1].tf2 = false
data[1].empty = null
data[1].name = Horatio
data[1].array[1] = 1
data[1].array[2] = 2
data[1].array[3] = 3
data[2].number = 2
data[2].integer = 33
data[2].real = 2.3330000000000001E+2
data[2].name = Nelson
rfc6901 tests.foo[1] = bar
rfc6901 tests.foo[2] = baz
rfc6901 tests.   = 0
rfc6901 tests.a/b = 1
rfc6901 tests.c%d = 2
rfc6901 tests.e^f = 3
rfc6901 tests.g|h = 4
rfc6901 tests.i\j = 5
rfc6901 tests.k"l = 6
rfc6901 tests.  = 7
rfc6901 tests.m~n = 8

printing each variable [JSONPath style]

$['version']['major'] = 2
$['version']['minor'] = 2
$['version']['patch'] = 1
$['version']['string'] = 2.2.1
$['version']['svn'] = 7191
$['files'][1] = ..\\path\\to\\files\\file1.txt
$['files'][2] = ..\\path\\to\\files\\file2.txt
$['files'][3] = ..\\path\\to\\files\\file3.txt
$['files'][4] = test \u2FA4 \uABCD \uABCD\uABCDtest
$['files'][5] =    test  \\u \" blah\\\" test test
$['files'][6] = ..\\path\\to\\files\\
$['a']['b'] = 1
$['escape'] =  \" \\ \/ \b \f \n \r \t
$['empty_array'] = ()
$['empty_object'] = {}
$['empty_string'] =
$['data'][1]['number'] = 1
$['data'][1]['tf1'] = true
$['data'][1]['tf2'] = false
$['data'][1]['empty'] = null
$['data'][1]['name'] = Horatio
$['data'][1]['array'][1] = 1
$['data'][1]['array'][2] = 2
$['data'][1]['array'][3] = 3
$['data'][2]['number'] = 2
$['data'][2]['integer'] = 33
$['data'][2]['real'] = 2.3330000000000001E+2
$['data'][2]['name'] = Nelson
$['rfc6901 tests']['foo'][1] = bar
$['rfc6901 tests']['foo'][2] = baz
$['rfc6901 tests']['  '] = 0
$['rfc6901 tests']['a/b'] = 1
$['rfc6901 tests']['c%d'] = 2
$['rfc6901 tests']['e^f'] = 3
$['rfc6901 tests']['g|h'] = 4
$['rfc6901 tests']['i\j'] = 5
$['rfc6901 tests']['k"l'] = 6
$['rfc6901 tests'][' '] = 7
$['rfc6901 tests']['m~n'] = 8

get some data from the file...
version%svn =  7191

version.svn =  7191

data(1).array(2) = 2

escape =  " \ /


data(1).tf1 = True

files(1) = ..\path\to\files\file1.txt

@(1)(1) = 2

files(2) = ..\path\to\files\file2.txt

files(3) = ..\path\to\files\file3.txt

data(2).real =         0.2333000000000000E+03

files[4] = test \u2FA4 \uABCD \uABCD\uABCDtest

files[5] =    test  \u " blah\" test test

empty_array =

files[10] not in file.

version.blah not in file.

 Test removing data from the json structure:
Runtime Error: /home/themos/json-fortran/src/json_value_module.F90, line
1991: Dangling pointer P%PREVIOUS used as argument to intrinsic function
ASSOCIATED
Target was DEALLOCATEd at line 1995 of
/home/themos/json-fortran/src/json_value_module.F90
Program terminated by fatal error
/home/themos/json-fortran/src/json_value_module.F90, line 1991: Error
occurred in JSON_VALUE_MODULE:JSON_VALUE_DESTROY
/home/themos/json-fortran/src/json_value_module.F90, line 1978: Called by
JSON_VALUE_MODULE:JSON_VALUE_DESTROY
/home/themos/json-fortran/src/json_value_module.F90, line 2099: Called by
JSON_VALUE_MODULE:JSON_VALUE_REMOVE
/home/themos/json-fortran/src/tests/jf_test_1.f90, line 293: Called by
JF_TEST_1_MOD:TEST_1
/home/themos/json-fortran/src/tests/jf_test_1.f90, line 500: Called by
JF_TEST_1
Aborted (core dumped)

**Comment by jacobwilliams** [comment]
I don't have access to the NAG compiler. I can take a look at the code to see if I see any problems, but it does work with both the Intel and Gfortran compilers.

**Comment by jacobwilliams** [comment]
Note to self: https://software.intel.com/en-us/forums/intel-fortran-compiler-for-linux-and-mac-os-x/topic/270495

**Comment by jacobwilliams** [comment]
Note: the original issue has been fixed. I'll make a new ticket for the other issue.
