### ISSUE TITLE
Question: Read a string array

### ISSUE THREAD

**Issue by chrschuster** [jacobwilliams/json-fortran#322]
Hi,

I am trying to read an array of strings. However gfortran cannot find a matching binding for the get call. I suspect I am defining the string array wrong, or am doing this not as intended. 
I am new to Fortran and Json, sorry if I am asking a stupid question. 
I did not find an answer to this issue elsewhere.

A code to reproduce the issue:
```fortran
program jsonStringArray
    use json_module
    implicit none
    
    type(json_file)               :: myFile
    character(len=:), allocatable :: string
    character(len=:), allocatable :: stringArray(:)
    
    call myFile%load_file('test.json')
    
    call myFile%get('string', string)
    call myFile%get('array', stringArray)
end program jsonStringArray
```
The json file:
```javascript
{
    "string": ["test"],
    "array": ["this", "is", "a", "test"]
}
```
The compile error:
```
$gfortran -cpp -Wall -fbounds-check  -I/usr/local/jsonfortran-gnu-6.3.0/lib/ -o jsonStringArray jsonStringArray.f90 
jsonStringArray.f90:12:15:

     call myFile%get('array', stringArray)
               1
Error: Found no matching specific binding for the call to the GENERIC ‘get’ at (1)
```

It works for the single string, but not for the array. What is my error, or how can I do this correctly?

Thank you!

P.S. Thanks for this awesome library!

**Comment by jacobwilliams** [comment]
See the `json_file_get_alloc_string_vec` routine for the correct interface. For strings like `character(len=:),dimension(:),allocatable :: vec`, Fortran requires all the lengths to be the same. So, the way I did it was to allocate it to length of the longest one, and then also return an integer array of the actual lengths of the elements. 

Warning: I think some older versions of fortran don't work properly for this routine.

**Comment by chrschuster** [comment]
Thank you for your fast response! Everything works as it should.
