### ISSUE TITLE
read only part of a big json file

### ISSUE THREAD

**Issue by mgovoni-devel** [jacobwilliams/json-fortran#341]
My file has many items (of a list), each item has lots of data, and it is impossible to load the whole file at once in memory (json%load_file). How do I load only a selected part of the file?
Actually, how do I: open the file, scan it to reach the element I want to read, then read only such element, and then close the file. 
Thanks.

**Comment by jacobwilliams** [comment]
I don't believe that is currently possible with the existing API. But that would be a nice feature... I need to think about it. 

Perhaps an optional argument to `load_file` where you give it the path to the variable you want, and then it only loads that one and not the whole thing?

Or is the one you want not known until you check what is in the file?

**Comment by mgovoni-devel** [comment]
Imagine you have a file structured in this way: 
{ 
"a" : [
{ "b" : 1, "c" : [ 0.00001, 0.00002, ... ] }, 
{ "b" : 2, "c" : [ 0.00001, 0.00002, ... ] }, 
{ "b" : 3, "c" : [ 0.00001, 0.00002, ... ] }
]}
where "c" elements are long arrays so that the file cannot be loaded all at once.
I would like to: 1) open the file, 2) iterate through the elements of the list "a" by loading only "b", 3) load "c" only when a condition is positive (e.g. when "b" == 2). 
A workaround to the above request is good too, as long as it doesn't imply loading the whole file at once. 
Thanks.

**Comment by mgovoni-devel** [comment]
Addendum. It would be also ok to load the items of "a" one by one, i.e. load both "b" and "c" (and all other keys related to that item). Some work is done to the array "c" based on the "b" value. Then the iteration can proceed to the next item. The important thing would be to have only one item (element of the "a" list) allocated in memory and not all of them.

**Comment by jacobwilliams** [comment]
I'm going to close this as beyond the scope of JSON-Fortran, since it would require a major rewrite of the parser. It would also complicate the get/set and pointer manipulation API since that assumes the entire structure is always in memory. A workaround would be to split up the large JSON files into multiple files and only read the ones you want.
