### ISSUE TITLE
Check validity of JSON file

### ISSUE THREAD

**Issue by mgovoni-devel** [jacobwilliams/json-fortran#359]
After `json%load_file(filename="xxx")`, how do I check that the file is valid (JSON syntax is ok)?

**Comment by jacobwilliams** [comment]
if `json%failed()` returns `.false.` then the file was successfully parsed. If not, then use `json%check_for_errors` to get the error message.

**Comment by mgovoni-devel** [comment]
Thanks. 
How about checking for validity against a given JSON schema?

**Comment by zbeekman** [comment]
@mgovoni-devel I do not believe that is implemented. I could be wrong. Could be a nice feature, but seems likely that it would be non-trivial to implement.

**Comment by jacobwilliams** [comment]
Yeah, there's nothing like that in JSON-Fortran. We've got methods (like `info` you could use to traverse a structure and check types, values, etc.) But, there's no automatic validation against a specific schema.
