### ISSUE TITLE
Cmake compile issue

### ISSUE THREAD

**Issue by cubayang** [jacobwilliams/json-fortran#376]
Message during cmake compilation: Variable {ME} in subroutine destroy_json_core(me) has not been used. Is it a big issue? Thanks!

**Comment by cubayang** [comment]
The above message is shown when I change the variable "ENABLE_TESTS" from "True" to "False". However, if I compile with "ENABLE_TESTS=True" which is the default setting, then I got a camke error: 

![capture](https://user-images.githubusercontent.com/10250229/48157731-6f9bed00-e29e-11e8-8a6b-7b24a264c2cc.PNG)

**Comment by cubayang** [comment]
I tested it on my Mac, it works well. Still the same error when I try to compile on Linux.

**Comment by zbeekman** [comment]
@cubayang which version of CMake are you using? And which linux OS?

**Comment by cubayang** [comment]
I tried on two different linux OS clusters, and one is working well, the other not.
The good one uses cmake 3.9.1, CentOS release 6.10, and the failed one uses cmake 2.8.12, CentOS Linux release 7.5.1804.

**Comment by zbeekman** [comment]
I think we probably need to bump the minimum required CMake version. Can you try installing a more recent CMake into your home directory on the other machine? You can download pre-built relocatable CMake binaries from: https://cmake.org/download/

I recommend the file named: cmake-3.12.4-Linux-x86_64.sh (https://cmake.org/files/v3.12/cmake-3.12.4-Linux-x86_64.sh). You can install into your home directory like this:

```
chmod +x cmake-3.12.4-Linux-x86_64.sh
./cmake-3.12.4-Linux-x86_64.sh --prefix=${HOME}/.local --exclude-subdir
```

Then make sure you add the appropriate bin directory in `~/.local` to your `$PATH`:
e.g.,
```
export PATH="${HOME}/.local/bin:$PATH"
```

**Comment by cubayang** [comment]
YES! It works after following your instructions. Many thanks!
