### ISSUE TITLE
problems for building the json-fortran by build.sh

### ISSUE THREAD

**Issue by QJohn2017** [jacobwilliams/json-fortran#379]
Hi, @zbeekman 
     This is my first time to build the json-fortran。Before I build the library, I have first installed the `FoBiS` by the guide manual in [this page](https://github.com/szaghi/FoBiS/wiki/Install). After installed the FoBiS, I began to build the json-fortran, but there are many problems occurred as following:
![1](https://user-images.githubusercontent.com/31507149/51237410-61a9cd00-19af-11e9-843b-b6c22335eaba.jpg)
![2](https://user-images.githubusercontent.com/31507149/51237412-62426380-19af-11e9-91a7-462e98411635.jpg)
![3](https://user-images.githubusercontent.com/31507149/51237414-62426380-19af-11e9-9599-64fb76cb35ed.jpg)

Is it something that I forgot to install before build the library? Thank you !

**Comment by jacobwilliams** [comment]
You need a more recent Fortran compiler (a newer gfortran or ifort) that supports the Fortran 2003/2008 features we are using.
