### ISSUE TITLE
Cleanup of API for reading and writing

### ISSUE THREAD

**Issue by jacobwilliams** [jacobwilliams/json-fortran#397]
I'm thinking of adding `read` and `write` generic procedures to replace (or that could be used in addition to) the various routines:

* json_file:load_file
* json_file:load_from_string
* json_file:print_file
* json_file:print_to_string
* json_core:parse
* json_core:print
* json_core:print_to_string

Or also maybe also consider UDDTIO?

**Comment by zbeekman** [comment]
UDDTIO would be really nice.

**Comment by dongli** [comment]
Why not just give users `json_file` and `json_value` objects, what is the meaning of `json_core`. I find difficulties to figure out the paradigm.

**Comment by jacobwilliams** [comment]
`json_file` is the high-level interface. `json_core` is a class with all the methods for manually manipulating the JSON pointer structures (this is available for use by the user if they want, and is also used internally by `json_file`).

**Comment by jacobwilliams** [comment]
Perhaps the new API should be:

```fortran
json_file.print
json_file.load
json_file.serialize
json_file.deserialize

json_core.print
json_core.load
json_core.serialize
json_core.deserialize
```
