### ISSUE TITLE
json_file%init(stop_on_failure=.true.) fails w/ json%add('two.paths', val)

### ISSUE THREAD

**Issue by zbeekman** [jacobwilliams/json-fortran#403]
When a `json_file` object is initialized with `stop_on_error=.true.` then followed by a `json%add('doesnt.existyet', 0.0_rk)` the program halts. I guess, presumably, under the hood you're creating new json pointers, and you check if they're there yet or not. This check is the one that halts the program.

This may not really be a bug, but it would be nice to have better control so that when statuses are checked and handled gracefully the program doesn't unexpectedly halt.

**Comment by jacobwilliams** [comment]
Yes, I can verify this. The reason is that sometimes exceptions are raised internally that eventually get cleared (such as this case). Those aren't well handled by `stop_on_error` since it will stop at the first exception even though the call would otherwise return normally. I can fix.
