### ISSUE TITLE
Intel compiler bug triggered by d2622a86f076f041ad8c971c42c42f7c5310f45b

### ISSUE THREAD

**Issue by zbeekman** [jacobwilliams/json-fortran#41]
My version of the Intel compiler doesn’t like having multiple TBPs declared in one `procedure :: …` statement. The fix is easy: move each TBP (introduced in d2622a86f076f041ad8c971c42c42f7c5310f45b) to its own line. I’m working up a pull request with this and some other stuff, so you can wait until I submit it if you like, rather than fixing it yourself. https://software.intel.com/en-us/forums/topic/538422

**Comment by jacobwilliams** [comment]
Interesting.  Yes, I'll just accept your fix when it's ready.

**Comment by jacobwilliams** [comment]
Hope I didn't mess you up to much.  I went ahead and committed this along with a bunch of other stuff that I was working on.

**Comment by zbeekman** [comment]
That’s fine… I made this fix, but I consider it too small/trivial for its own pull request. The refactoring and improvements on the testing suite (#30 and #27) proved to be slightly more involved than I anticipated… This looks fixed by 1337f260663e5665f7f5cbcb9bc38f4bb4591160 so I’m going to close this issue.
