### ISSUE TITLE
Support for floating point numbers without leading zeros

### ISSUE THREAD

**Issue by zimmermm** [jacobwilliams/json-fortran#417]
Hi Jacob
I'd be happy if your library supports the following floating-point number notations in the JSON file:
- .5 instead of 0.5
- 1.2D-5 as the notation for double-precision numbers

**Comment by jacobwilliams** [comment]
Be aware those are not valid JSON numeric values. But, I can add support for them as an extension (via an optional argument to `initialize`). I was also thinking of allowing positive numbers that start with `+` (also invalid in JSON).

**Comment by zimmermm** [comment]
yes, I am aware of that. We use JSON as an input-file format for our model. But now we use a calibration software where we can't control the number format. There are other workarounds for that but I thought if it is possible to extend your library to non-standard formats this would be a nice solution.
Support for comments would be a nice thing too but is also not valid.

**Comment by jacobwilliams** [comment]
Note: comments are supported! Use the optional `comment_char` input to `initialize` to set the character to use for comments (e.g., `'!'`, `'#'` or `'\'`).
