### ISSUE TITLE
Segfault in test 10 with GFortran 8.3.0 on macOS

### ISSUE THREAD

**Issue by zbeekman** [jacobwilliams/json-fortran#422]
I suspect there is a memory leak, dangling pointer, or uninitialized variable somewhere. It can't be reliably reproduced (and could be a compiler bug) but if I run

```
ctest --repeat-until-fail 7 --schedule-random -j 12
```

on a macOS MBP with 6 physical cores & 12 logical cores I can usually get test 10 to segfault. Probably should throw valgrind at it on a linux box.

**Comment by jacobwilliams** [comment]
I see this also with gfortran 9.1.0. Will investigate.
