### ISSUE TITLE
JSON Interoperability: C and Fortran

### ISSUE THREAD

**Issue by nyckmaia** [jacobwilliams/json-fortran#429]
Is there any way to use C / Fortran Interoperability (bind C) to send a JSON document from a C application to Fortran subroutine?

**Comment by jacobwilliams** [comment]
Yes, that's possible. You'd need some wrapper code, similar to what I show here: http://degenerateconic.com/fortran-json-python/ (see `c_ptr_to_json`).

**Comment by jacobwilliams** [comment]
Note: I also have in mind one day to write a C API for JSON-Fortran so you can call it directly from C. But I haven't done any work on that. There is a ticket: #371
