### ISSUE TITLE
Error adding array

### ISSUE THREAD

**Issue by nyckmaia** [jacobwilliams/json-fortran#432]
I loaded a **existent JSON file** using:
```
call json%load_file(filename = lpath)
```
I can insert new fields in it using `call json%update('new_field', 1, found)`. **It works well.**
But when I tried to insert a new **array field** like this:
```
call json%update('a.b.c', [1, 2, 3], found)
```
I got a **compiler error:**
```
error #8486: There is no matching specific subroutine for this type bound generic subroutine call.   [UPDATE]
```
I would like to get a JSON file like this:
```
{
    "a": {
        "b": {
            "c": [1, 2, 3]
        }
    }
}
```

**How can I insert a new array field in a existent JSON file?**

**Comment by jacobwilliams** [comment]
I don't think `update` works for arrays. Try `add`.

**Comment by nyckmaia** [comment]
@jacobwilliams the problem to use `add` is that I'm loading a existent JSON file...so I understand that I have to use `type(json_file) :: json` instead of `type(json_core) :: json`.

But when I use `type(json_file) :: json` I don't have access to the `add` method.

Right?

**Comment by jacobwilliams** [comment]
There is an `add` method in `json_file`, so it should work.

What are you trying to do exactly? Do you want to append elements to an existing array, or just add an array to the structure?

**Comment by jacobwilliams** [comment]
Example:

Say, `test.json` contained:

```json
{"x": 1}
```

Then:

```fortran
program main
use json_module 

implicit none

type(json_file) :: json 

call json%load('test.json')
call json%add('a.b.c', [1, 2, 3])
call json%print()

end program main
```

gives the following result:

```json
{
  "x": 1,
  "a": {
    "b": {
      "c": [
        1,
        2,
        3
      ]
    }
  }
}
```
