### ISSUE TITLE
undefined reference to  `__json_file_module_MOD___vtab_json_file_module_Json_file' when compiling

### ISSUE THREAD

**Issue by lsmenicucci** [jacobwilliams/json-fortran#439]
Good night, I'm having a problem using the json_module. Whenever i try to call a subroutine of a `json_file` instance, I get a compilation error like this:

```bash
/path/to/my/file.f08:19: undefined reference to `__json_file_module_MOD___vtab_json_file_module_Json_file'
```

For example, the following code
```Fortran
MODULE io
    USE json_module
    USE Variables

    CONTAINS 
    
    SUBROUTINE test_subroutine()
        IMPLICIT NONE
  
        type(json_file) :: f

        call f%initialize()
        call f%load_from_string('{ "name": "Leonidas" }')

    END SUBROUTINE
 
END MODULE io
```

Would result on:
```
/path/to/my/file.f08:12: undefined reference to `__json_file_module_MOD___vtab_json_file_module_Json_file'
/path/to/my/file.f08:12: undefined reference to `__json_file_module_MOD_initialize_json_core_in_file'
/path/to/my/file.f08:13: undefined reference to `__json_file_module_MOD___vtab_json_file_module_Json_file'
/path/to/my/file.f08:13: undefined reference to `__json_file_module_MOD_json_file_load_from_string'
```

  I'm currently using meson and ninja on a Ubuntu WSL environment to build my project dependencies. I've also installed the json-fortran library with cmake on the directory `/usr/local/jsonfortran-gnu-7.1.0` and the json-fortran package is correctly listed on pkg-config.

**Comment by jacobwilliams** [comment]
I don't have any experience with meson, ninja, or WSL, so I'm not sure how to help.

Are you able to compile and run the tests?

**Comment by lsmenicucci** [comment]
I'm sorry, I forgot to add json-fortran as a dependency on my test driver. Everything works fine, even with meson and ninja on WSL. Keep up with the nice work you've done on this library!
