### ISSUE TITLE
Example 8 failing on gfortran 4.9.2

### ISSUE THREAD

**Issue by jacobwilliams** [jacobwilliams/json-fortran#44]
Just noticed that Example 8 (Valid test 2) is not giving the correct output when compiled with gfortran 4.9.2.  I think it is a compiler bug, since it works on gfortran 5 and ifort.  Will look into it.  Maybe there is a simple workaround.  The error message is odd also, since it is encountering a ```!``` character, which isn't in the string:

```
Error in parse_object: Expecting end of object: !
line: 5, character: 1
}
^
```
This is one of the examples where the json structure is read from a string.

**Comment by zbeekman** [comment]
on gfortran 4.9.0 the output appears correct.
```
**************
 Valid test 2:
**************

{
  "label": "foo",
  "value": "bar",
  "empty_array": [],
  “empty_object”: {}
}
```

**Comment by jacobwilliams** [comment]
Looks like its another allocatable character string issue. I committed a workaround. See: bc4166a6ee

**Comment by jacobwilliams** [comment]
See also Issue #5.
