### ISSUE TITLE
CMake configuration failure 

### ISSUE THREAD

**Issue by cwcatkins** [jacobwilliams/json-fortran#442]
Hi,

When building using CMake v3.3.1 an error is returned:
```
CMake Erroat CMakeLists.txt:388 (if):
  if given arguments:
    "CMAKE_VERSION" "VERSION_GREATER_EQUAL" "3.14"
  Unknown arguments specified.
```
The configuration then fails. 

I think this is due to VERSION_GREATER_EQUAL not being available in CMake 3.3.1, only VERSION_GREATER is:
https://cmake.org/cmake/help/v3.3/command/if.html

After changing the if statement the code compiled.

Kind Regards,

Chay

**Comment by jacobwilliams** [comment]
@zbeekman  Any thoughts on this?

**Comment by zbeekman** [comment]
yes sounds like @cwcatkins has figured out what's up. I think it might be worthwhile bumping the minimum cmake required, at this point even 3.3 is pretty ancient.

**Comment by jacobwilliams** [comment]
For, now I can just change it to this:
```cmake
  if(CMAKE_VERSION VERSION_GREATER 3.13.5)
```
