### ISSUE TITLE
Please document the cmake build instructions

### ISSUE THREAD

**Issue by rouson** [jacobwilliams/json-fortran#455]
Most importantly, it's not clear how to build all of the tests.  My steps were
```
git clone git@github.com:jacobwilliams/json-fortran
mkdir -p json-fortran/build
cd json-fortran/build
cmake ..
make -j 8
```
after which I was able to build each individual test in a manner such as
```
make jf_test_01
```
but I couldn't find instructions in the README.md or on the wiki for building all of the tests at once.  I tried `make test` and `make tests` to no avail.

**Comment by jacobwilliams** [comment]
`make check` is what you want I believe. This should build the unit tests and run them.

I can update the documentation. Note: I usually use FoBiS to build them (e.g., `FoBiS.py build -f json-fortran.fobis -mode tests-gnu`).
