### ISSUE TITLE
Issues with "input%get" when requesting a pointer

### ISSUE THREAD

**Issue by idmozom** [jacobwilliams/json-fortran#457]
Thank you first for this great work. I am working with the routine `input%get` to read variables and load pointers. Initially, I was reading the next file:

![image](https://user-images.githubusercontent.com/65001430/81367547-315dd480-90b3-11ea-9a99-f3f061264993.png)

with the following code:

![image](https://user-images.githubusercontent.com/65001430/81368507-87337c00-90b5-11ea-8bb7-04ad4cf5bd0a.png)

![image](https://user-images.githubusercontent.com/65001430/81368523-90bce400-90b5-11ea-877d-4021de607cec.png)

So far no problem. When I try to read the following file with the same code, "WELLDATA" is not found by the subroutine `input%get`. 

![image](https://user-images.githubusercontent.com/65001430/81367938-25264700-90b4-11ea-9a98-dd8154260299.png)

The code must be the same because the fields of the file may or may not exist.

thanks for your help.

**Comment by jacobwilliams** [comment]
Can you post the code and files as text rather than as screenshots? That would make it easier for me to try and see what the problem is.

**Comment by idmozom** [comment]
Hi, this is the program code:

`main program`

	Program Main

		Use Global
		Implicit None 

		Call read_data 

	End program

`read_data`

	Subroutine read_data
	
		Use Global
		Implicit None 
		
		Call input%initialize()
	 	Call input%load_file('input.json')	
		
		Call read_json
	
	End Subroutine

`read_json`

	Subroutine read_json
		
		Use Global
		implicit None 
				
		Call input%get('NUMERICAL.TSTEPCONT.MAXDT',MaxDt,Found)
		Call input%get('NUMERICAL.TSTEPCONT.MINDT',MinDt,Found)
		Call input%get('NUMERICAL.TSTEPCONT.DTSTART',DtStart,Found)
		Call input%get('NUMERICAL.TSTEPCONT.DTMULT',DtMult,Found)
		Call input%get('NUMERICAL.TSTEPCONT.MAXCUTS',MaxCuts,Found)
		
		Call input%get('NUMERICAL.MAXVAR.PRES',MaxPreDt,Found)
		Call input%get('NUMERICAL.MAXVAR.TEMP',MaxTemDt)
		Call input%get('NUMERICAL.MAXVAR.SAT',MaxSatDt,Found)
		Call input%get('NUMERICAL.MAXVAR.CON',MaxConDt,Found)
		
		Call input%get('NUMERICAL.NEWTONSOL.MAXNEWIT',MaxNewIt,Found)
		Call input%get('NUMERICAL.NEWTONSOL.MINNEWIT',MinNewIt,Found)
		Call input%get('NUMERICAL.NEWTONSOL.NEWTOL',NewTol,Found)
					
		Call input%get('NUMERICAL.LINEARSOL.MAXSOLIT',MaxSolIt,Found)
		Call input%get('NUMERICAL.LINEARSOL.MINSOLIT',MinSolIt,Found)
 
		Call input%get('WELLDATA',pointaux,Found)
		Call json%info(pointaux,var_type,n_children,name)	
		
	End Subroutine

`global variables`

	Module Global 
	
		Use json_module
		Type(json_file):: input
		Type(json_value), pointer :: pointaux
		type(json_core) :: json
		Character(kind=json_CK,len=:), allocatable :: name
		Integer:: var_type, n_children
	
		Logical:: Found
		
		Real*8:: MaxDt, MinDt, DtStart, DtMult, NewTol
		Integer:: MaxCuts, MaxNewIt, MinNewIt, MaxSolIt, MinSolIt
		Real*8:: MaxPreDt, MaxTemDt, MaxSatDt, MaxConDt, MaxPreTS, MaxTemTS, MaxSatTS, MaxConTS
		
	End Module 

`input.json`

{
  "NUMERICAL": {
    "TSTEPCONT": {
      "MAXDT": 30,
      "MINDT": 1E-7,
      "DTSTART": 0.5
    }
  },

  "NUMERICAL2": {
    "TSTEPCONT": {
      "MAXDT": 30,
      "MINDT": 1e-7,
      "DTSTART": 0.5,
      "DTMULT": 2,
      "MAXCUTS": 8
    },
    "MAXVAR": {
      "PRES": 1450,
      "TEMP": 400,
      "SAT": 0.2,
      "CON": 0.2
    },
    "NEWTONSOL": {
      "MAXNEWIT": 20,
      "MINNEWIT": 3,
      "NEWTOL": 1E-6
    },
    "LINEARSOL": {
      "MAXSOLIT": 150
    }
  },

  "WELLDATA": {
    "0.0": {
    },
    "10.0": {
    }
  }

}

I use intel fortran 2020 as compiler and visual studio 2019. The error appears in debug and release mode. 

thanks for your help.

**Comment by jacobwilliams** [comment]
This line: `Call input%get('NUMERICAL.MAXVAR.TEMP',MaxTemDt);` doesn't have a `found` output, and this variable isn't in the file. So it it raising an exception in `input`. (you can test exceptions using `input%failed()`.
