### ISSUE TITLE
json_file_variable_info and path names containing "@"

### ISSUE THREAD

**Issue by rsf83F4qW26jC6MVqBVC** [jacobwilliams/json-fortran#458]
For the file containing

```json
"ABC":{
    "bl@ah":{
        "domain":0.0
    }
}
```

then the call ```CALL json%info("ABC.bl@ah.domain",found=found)``` results in found=.FALSE.  Removing "@" from both the file and the subroutine call works exactly as expected, as does everything else I have tried to date.  It doesn't seem that "@" is a special character in JSON.  Any ideas?  Thanks.

**Comment by jacobwilliams** [comment]
Yes `@` is a special character for getting the path for the default path mode (in addition to `.`, `()`, etc.). See `json_get_by_path_default()`. There are two other `path_mode` options you can use that have different syntax if necessary. See the `path_mode` input to the `initialize` routines.

**Comment by rsf83F4qW26jC6MVqBVC** [comment]
Ah, ok, got it.  Thanks for the heads up.
