### ISSUE TITLE
Max length for compress_vectors

### ISSUE THREAD

**Issue by vincentmr** [jacobwilliams/json-fortran#460]
When printing to a file with compress_vectors = .true., vectors containing more than 1000 elements, double precision numbers in my case, are not compressed. Is that expected behaviour? If so, is there a way to increase the limit of the number of elements that get printed on one line?

**Comment by jacobwilliams** [comment]
Interesting. What compiler are you using?

This might be some compiler limit to the length of line that can written in a formatted write statement (I know ifort has some kind of limit for read statements). 

I'd need to look into it to see what can be done about it.

**Comment by vincentmr** [comment]
I'm using GCC. 
`$ gcc --version

gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
`

**Comment by jacobwilliams** [comment]
Does this example show the bug for you? It works fine for me with gfortran 9.3.0:

```fortran

program test

use json_module, RK => json_RK

!! testing of compress_vector for large arrays

implicit none

type(json_file) :: json
real(RK),dimension(:),allocatable :: array
integer :: i !! counter
integer :: iunit

integer,parameter :: n_elements = 2000

open(newunit=iunit,file='long_line.json',status='REPLACE')

array = [(1.0_RK, i=1,n_elements)]

call json%initialize(compress_vectors = .true.)
call json%add('array',array)
call json%print(iunit)

if (json%failed()) error stop 'error'

call json%destroy()

close(iunit)

end program test
```

**Comment by vincentmr** [comment]
It turns out my issue has nothing to do with length (your example works fine with gcc 7.3). My problem originates from a json encoder (MATLAB's) printing certain real numbers as integers. It seems that when there is a number without a dot in a real vector, the json object will fail to reprint the vector in compressed form. For example, below the vector [0,1.0,2.0] which is originally on one line is reprinted as a column. So maybe the issue belongs to MATLAB, but if this is easily fixable you might consider solving it in json-fortran.     
`program test

   use json_module, RK => json_RK
   
   !! testing of compress_vector for large arrays
   
   implicit none
   
   integer, parameter            :: dp  = selected_real_kind(15, 307)    !< double precision float
   integer, parameter            :: n_elements = 10000
   type(json_file)               :: json
   real(dp), allocatable         :: array(:)
   integer                       :: i !! counter
   integer                       :: iunit
   character(len=:), allocatable :: jsonstring

   jsonstring = '{"array":[0,1.0,2.0]}'

   open(newunit=iunit,file='vector.json',status='REPLACE')
   write(iunit,*) jsonstring
   close(iunit)  
   
   allocate(array(n_elements))
   call random_number(array)

   ! reload input file
   open(unit = 1, iostat = iunit, file = 'long_line.json', status = 'REPLACE')
   if (iunit == 0) close(1, status='delete')
   call json%initialize(compress_vectors = .true.); call json%load_file('vector.json')
   call json%add('long_array',array)
   call json%print_file('long_line.json')
   call json%destroy()

end program test`

**Comment by jacobwilliams** [comment]
Ah, yes, that is the expected behavior. JSON-Fortran treats "0" as a integer and "0.0" as a real. The `compress_vectors` option only works if every element of the array is the same type.

I could change it so that it will allow for mixed ints and reals and still work?

**Comment by vincentmr** [comment]
> I could change it so that it will allow for mixed ints and reals and still work?
That would be nice.
