### ISSUE TITLE
Passing JSON as parameter

### ISSUE THREAD

**Issue by ghost** [jacobwilliams/json-fortran#467]
I'm developing a C++ application that uses `nlohmann::json` API.
Link here: [https://github.com/nlohmann/json](https://github.com/nlohmann/json)

I would like to call a Fortran function passing a JSON as a input argument.

```c
extern "C" {
    void my_fortran_fun(nlohmann::json myJson);
}

int main() 
{
...
    my_fortran_fun(my_json);
---
}
```

**Is it possible?**

**Comment by jacobwilliams** [comment]
JSON-Fortran isn't going to understand the C++ structure (and C++ isn't going to understand the Fortran structure). Probably you could do it by serializing the JSON to a string?

**Comment by jacobwilliams** [comment]
See also #371 and #429.
