### ISSUE TITLE
Avoid hard stop when a key does not exist in json

### ISSUE THREAD

**Issue by AliE89** [jacobwilliams/json-fortran#473]
Hello jacob,
Thank you very much for sharing this library! 
This is not an issue, but it is more a question. Is there a way to avoid getting an error, if a key is not present in the json? Maybe having return an error code or a logical flag instead of an hard stop?

Many thanks!

**Comment by jacobwilliams** [comment]
There shouldn't be any hard stop if a key isn't found. If you use the `found` optional argument, it will be set to false. If you don't, an exception will be raised, which you can also handle. Do you have example code where it it stopping?

**Comment by EvgeniyMist** [comment]
> There shouldn't be any hard stop if a key isn't found. If you use the `found` optional argument, it will be set to false. If you don't, an exception will be raised, which you can also handle. Do you have example code where it is stopping?

I faced this problem too, here is the test program:
```
program test
    use json_module
    implicit none

    integer :: int_var
    type(json_file) :: json
    logical :: bool_var, found_var

    call json%initialize(stop_on_error=.true.)
    call json%load(filename='test.txt')
    call json%get('int_var', int_var)
    print *, int_var
    call json%get('bool_var', bool_var, found=found_var)
    ! call json%json_file_variable_info('bool_var', found=found_var)
    ! found_var = json%valid_path('bool_var')
    print *, found_var
    call json%destroy()
end program test
```
And extremely simple `test.txt`:
```
{
    "int_var": 5
}
```
So program has stopped with this message:
```
JSON-Fortran Exception: Error in json_value_get_child_by_name: child variable bool_var was not found.
ERROR STOP 1
```
Other methods, which I found in the documentation and which are now commented out, give exactly the same result.
