### ISSUE TITLE
How to initialize real_fmt

### ISSUE THREAD

**Issue by jjure** [jacobwilliams/json-fortran#475]
Hello,

this is just a (newbie) question: 

It seems I am missing something obvious here:
What is the proper way to setup the number of decimal places when printing out reals? 
I can't see the way how to specify real_fmt in json%initialize.

Thank you!

**Comment by jacobwilliams** [comment]
```fortran
call json%initialize(real_format='E')
```

The valid choices are 'E' [default], '*', 'G', 'EN', or 'ES'. Note that you can't set the number of decimal places, since that is computed automatically based on the real kind you are using.
