### ISSUE TITLE
Switch CI to GitHub Actions

### ISSUE THREAD

**Issue by jacobwilliams** [jacobwilliams/json-fortran#476]
Look into this.

**Comment by yousef92-tech** [comment]
building the workflow, gfortran-6 is not available in ubuntu apt. only gfortran-7 and up.

**Comment by jacobwilliams** [comment]
Reference: https://docs.github.com/en/actions/reference/environment-variables

**Comment by jacobwilliams** [comment]
OK going to merge to master and see if the new doc deployment works!
