### ISSUE TITLE
size of subdictionary?

### ISSUE THREAD

**Issue by AliE89** [jacobwilliams/json-fortran#478]
Hello Jacob,

A silly question for you. Do we have a way to get the size of a sub-dictionary and iterate on its keys? 

Example:
```
{

"var": var,
"var2": var2,

dict1:{
  "a": 1
   "b": 2
   "c": 3
}

}
```
I would like to determine the size of dict1 (3 in this case) and then retrive the values associated with its key in a do loop.

thanks!

**Comment by schoonovernumerics** [comment]
You can use the info call with the `n_children` output assigned, e.g.
```
json % info('dict1', n_children=dict1_size)
```
Assuming that `json` is a JSON_FILE object.

**Comment by AliE89** [comment]
Thank you Joseph! Do you know also how I can iterate on the dict1 keys? 

Basically the same way you would do in python:
for key in dict1.keys():
    !do something with key

**Comment by schoonovernumerics** [comment]
I'm not sure how you would find they keys; perhaps check the [API documentation](http://jacobwilliams.github.io/json-fortran/) ?

You might consider changing your json file schema to where the keys are known. For example
```
{
  "var": var,
  "var2": var2,
  "dict1": [
    {
       "name": "a"
       "value: 1
    },
    {
       "name": "b"
       "value: 2
    },
    {
       "name": "c"
       "value: 3
    },
  ]
}
```
With this format, you can do something like
```
TYPE(JSON_FILE) :: json
TYPE(JSON_VALUE), POINTER :: objPointer, dict1Pointer, p
TYPE(JSON_CORE) :: jCore

 CALL json % Initialize()
 CALL json % Load(filename = '/path/to/your.json')
 json % info('dict1', n_children=dict1_size)
 
 DO i = 1, dict1_size
     CALL jCore % get_child(objPointer, i, dict1Pointer, found)
     IF( found )THEN

     ! Get dict1[].name
     CALL jCore % get_child(dict1Pointer, 'name', p, keyFound)
     IF( keyFound )THEN
       CALL jCore % get(p, dict1Name)
     ENDIF

     ! Get dict1[].value
     CALL jCore % get_child(dict1Pointer, 'value', p, keyFound)
     IF( keyFound )THEN
       CALL jCore % get(p, dict1Value)
     ENDIF
   ENDIF
 ENDDO
```

**Comment by AliE89** [comment]
Hello Joseph,

Thanks for the suggestion, i can try out your solution, many thanks.

I have checked the api but did not found anything that allow me to loop
over keys, perhaps that can be a usefull addition if one of the developers
have time :) the only thing I found is the traverse function even if i can
get a string of all the entries which is not easy to handle.

**Comment by schoonovernumerics** [comment]
@jacobwilliams wrote up a [thorough contributing guide](https://github.com/jacobwilliams/json-fortran/blob/master/.github/CONTRIBUTING.md). 

It may be worth hashing out here a concrete description of a new API call that could be added to accomplish what you're looking for.

**Comment by jacobwilliams** [comment]
Note that `get_child` also works on objects (as well as arrays) so you can use that for the original dict. 

There is also `get_next` which gives you the pointer to the next one in the list. So you would first get the first element, then use `get_next1` to get the subsequent ones.

I don't think I have either of these in the `json_file` API. Perhaps that would be useful?

**Comment by AliE89** [comment]
Hello Guys,

actually, I have found a way to do what I need following Joseph's idea:

        call jcore%initialize()

  ! get a pointer to my json file
        call json%get(dictPointer)

  ! get a pointer to "dict1"
        call jcore%get_child(dictPointer, 'dict1', objPointer, found)

   !  get a pointer to "subdict"
        call jcore%get_child(objPointer, 'subdict', subdict_pointer,
found_subdict)

  ! find out number of subdict keys
        call json%info('dict%subdict', n_children=subdict_size)

        DO i = 1, subdict_size

            ! get a pointer to the key
            CALL jcore%get_child(subdict_pointer, i, keyPointer, found)

            ! get path and value as strings (I can split by "." or "%" the
path to get the actual key name)
            if( found )then
                call jcore%get_path(keyPointer, path, keyFound)
                call jCore%get(keyPointer, dict1Value)
                write(*,*) path, " " ,dict1Value
            else
                write(*,*) 'NOT FOUND!'
            endif

        ENDDO

That looks ok to me.  @jacobwilliams, maybe worth adding a procedure that
takes as input a path and returns keys and values stored in the target
object? I think it can be handy :)

**Comment by jacobwilliams** [comment]
I'll close this issue, and think about that some more.

**Comment by AliE89** [comment]
Yeah, I found a work around thanks to, this discussion. Cheers
