### ISSUE TITLE
Support Fortran Package Manager

### ISSUE THREAD

**Issue by jacobwilliams** [jacobwilliams/json-fortran#483]
Add support for the [Fortran Package Manager](https://github.com/fortran-lang/fpm)

**Comment by awvwgk** [comment]
I think Carlos (@brocolis) has a fork with support for *fpm* already (see https://github.com/brocolis/json-fortran/commit/0c0d36f0280e81524561b44b3e6467e003a363ef).

**Comment by jacobwilliams** [comment]
Initial experiment here: 9d5802d93056c81453f708da6f8cf7a7420b4d8e
