### ISSUE TITLE
Cmake (Json-fortran 6.3.0)

### ISSUE THREAD

**Issue by 13015339981** [jacobwilliams/json-fortran#487]
Hi,all
 I tried to compile, but the following error occurred, how can I solve it?
`> cmake ..
CMake Error at cmake/checkOutOfSource.cmake:12 (message):
  Error, in source builds are not supported.  If you really want an in source
  build (and know what you are doing) you may set the advanced
  ENABLE_IN_SOURCE_BUILDS variable to ON.  Otherwise create a build directory
  not matching the source directory,
  '/lustre/home/acct-phy-mchen/phy-mchen/jyhua/QuickPic/json-fortran-6.3.0'.
Call Stack (most recent call first):
  CMakeLists.txt:29 (include)

-- CMake build configuration for JSON-Fortran 6.3.0
CMake Warning at CMakeLists.txt:224 (message):
  FORD not found! Please set the CMake cache variable FORD to point to the
  installed FORD executable, and reconfigure or disable building the
  documentation.  FORD can be installed from PYPI with `sudo pip install
  FORD` or from <https://github.com/cmacmackin/ford> If you do not wish to
  install FORD and build the JSON-Fortran documentation, then please set the
  CMake cache variable SKIP_DOC_GEN to TRUE.

-- Configuring incomplete, errors occurred!
See also "/lustre/home/acct-phy-mchen/phy-mchen/jyhua/QuickPic/json-fortran-6.3.0/CMakeFiles/CMakeOutput.log".
`
How can I modify it "ENABLE_IN_SOURCE_BUILDS = NO"?
Thanks.

**Comment by 13015339981** [comment]
[CMakeOutput.log](https://github.com/jacobwilliams/json-fortran/files/6775045/CMakeOutput.log)
![image](https://user-images.githubusercontent.com/43660935/124714537-7807c280-df34-11eb-8e17-2b14a916aa33.png)

**Comment by jacobwilliams** [comment]
Did you try:

```
mkdir build
cd build
cmake -D SKIP_DOC_GEN=TRUE ..
```
