### ISSUE TITLE
Tests directory should be subdirectory of src

### ISSUE THREAD

**Issue by zbeekman** [jacobwilliams/json-fortran#49]
While working on #27 and #30 I discovered that ROBODoc is no longer building documentation for the `tests/` because it has been moved outside of `src/` and ROBODoc only accepts one `--src` flag. Telling ROBODoc to look in the project root is less than ideal because CMake copies the source files to a build directory which I usually keep as an un-versioned subdirectory of the project root. My proposed solution is to move `tests/` into `src/` so that ROBODoc will recursively find the test sources too, without finding copies of sources in the build tree.

**Comment by jacobwilliams** [comment]
That's fine.  I think I moved it due to a FoBiS bug that has since been fixed... I don't quite recall.
