### ISSUE TITLE
Exported CMake target is incomplete

### ISSUE THREAD

**Issue by awvwgk** [jacobwilliams/json-fortran#503]
The exported CMake target is currently incomplete, *i.e.* the required include directory is not associated with the target. Also, the user has to work with the library target, rather than getting an imported library with namespacing.

This requires users of to fixup the *jsonfortran* target, *e.g.* by creating their own interface library. I'm currently using the following boilerplate:

```cmake
if(NOT TARGET "jsonfortran::jsonfortran" AND WITH_JSON)
  # json-fortran tries to make it hard to get found
  string(TOLOWER "jsonfortran-${CMAKE_Fortran_COMPILER_ID}" jsonfortran)
  find_package("${jsonfortran}" REQUIRED)
  add_library("jsonfortran::jsonfortran" IMPORTED INTERFACE)
  target_link_libraries(
    "jsonfortran::jsonfortran"
    INTERFACE
    "jsonfortran$<$<NOT:$<BOOL:BUILD_SHARED_LIBS>>:-static>"
  )
  target_include_directories(
    "jsonfortran::jsonfortran"
    INTERFACE
    "${jsonfortran_INCLUDE_DIRS}"
  )
endif()
```

Would it be possible to export a complete target (`jsonfortran::jsonfortran`) in this projects CMake files? I would be happy to contribute the required changes to the CMake build files.

**Comment by jacobwilliams** [comment]
I'm not really a CMake guru. So if you think there's some way to improve the CMake support feel free to send a merge request!

**Comment by jacobwilliams** [comment]
@awvwgk Thank you for the pull request. I can merge it in. Is there anything that should be said about this in the Readme? (again, this cmake stuff is not my strong suit).
