### ISSUE TITLE
conda-forge

### ISSUE THREAD

**Issue by jacobwilliams** [jacobwilliams/json-fortran#507]
See #506

**Comment by jacobwilliams** [comment]
@awvwgk This is great! I have some questions:

* can you explain exactly how you did this? How something ends up on condo has always been a mystery to me. 
* it would be nice to have windows also
* is it currently only for gnu? can we also have intel versions?
* is this the shared library build? Do you have an example of how a user's application might link with this after conda installing it?

**Comment by awvwgk** [comment]
> can you explain exactly how you did this? How something ends up on conda has always been a mystery to me.

The usual workflow is:
1. Somebody creates a recipe (see https://github.com/conda-forge/staged-recipes/pull/17555)
   - anyone can submit, you don't have to be a member of conda-forge
   - a recipe is just the [`meta.yaml`](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html) and maybe also a [`conda_build_config.yaml`](https://docs.conda.io/projects/conda-build/en/latest/resources/variants.html) (mainly used for MPI)
   - there is an extensive documentation on building recipes for conda-forge at https://conda-forge.org/docs/maintainer/adding_pkgs.html
   - the recipe gets reviewed and merged
2. From here the conda-forge bot fleet will convert the recipe into a feedstock (basically a repository to "harvest" free CI resources to build the recipe into actual conda binary packages)
3. Feedstock maintainers update the feedstocks or accept automatic updates provided by the bots (called migrations)
    - if you want to be added as maintainer to json-fortran, just let me know

> it would be nice to have windows also

Yeah, that would be nice to have. No promises, though (last time I tried there was an error).

> is it currently only for gnu? can we also have intel versions?

Only GCC at the moment. Intel and conda-forge still haven't decided whether it is okay to use their compilers at the scale of several thousand packages, unfortunately (some legal stuff about redistribution).

> is this the shared library build? Do you have an example of how a user's application might link with this after conda installing it?

The shared lib is available. I should use it in my [mctc-lib](https://github.com/conda-forge/mctc-lib-feedstock), but didn't get around to rebuild the packages yet.

> How is this to be maintained in the future for updates? is it automatic if I push a new release tag? I'm guessing not and somebody (you?) would have to do something? What is that process?

Conda-forge has an impressive automation for this purpose. You tag a release, a bot picks it up, updates the recipe and sends a PR, all I have to do is merge it (or tell another bot to merge it if it passes CI). If you like I can add you as a maintainer, most feedstocks are almost no work (I'm currently maintaining ~40 feedstocks at conda-forge).

**Comment by awvwgk** [comment]
@jacobwilliams Let me know if you have any further questions regarding the conda-forge ecosystem.

**Comment by jacobwilliams** [comment]
Thanks! Very nice. Yep, could you go ahead and add me as a maintainer? Just in case I need to do something for whatever reason maybe? (I'm perfectly happy for you to do all the work though.)

Otherwise, I'm ready to merge this if it's ready to go.

**Comment by awvwgk** [comment]
> Yep, could you go ahead and add me as a maintainer?

See https://github.com/conda-forge/json-fortran-feedstock/commit/8a7ddd314f54eb448389c4a10568c70f1f657ba9#commitcomment-64802870
