### ISSUE TITLE
writing err_message without call to throw_exception in son_parse

### ISSUE THREAD

**Issue by zbeekman** [jacobwilliams/json-fortran#51]
I *think* this *might* be a bug: [`son_parse` writes an `err_message` without calling `throw_error`](https://github.com/jacobwilliams/json-fortran/blob/master/src/json_module.f90#L4083) but I am not 100% sure. What do you think @jacobwilliams?

**Comment by jacobwilliams** [comment]
It's not a bug. An exception has already been thrown, and this is just adding additional information.

**Comment by zbeekman** [comment]
Ah, I see thanks for clarifying. I'll close once I'm back at a computer.
