### ISSUE TITLE
Suggestion for building with INT64 using fpm

### ISSUE THREAD

**Issue by sainttttt** [jacobwilliams/json-fortran#515]
Hi! I was wondering what would you recommend the best way to use json-fortran as a dependency for another project using fpm, but also getting it to use INT64. Building it using FoBiS and manually including the library works for me, but I'm not sure what the best way to do this using fpm - or if there is a way at all at the moment. I was wondering what would you recommend? 

Thanks!

**Comment by jacobwilliams** [comment]
I think including `--flag "-DINT64"` in the `fpm build` command will work?

**Comment by sainttttt** [comment]
Thanks, that seems to work great! My next question would be how would I include json-fortran as a dependency in another fpm project but specifying it to build with DINT64?

**Comment by sainttttt** [comment]
Thank you that works!
