### ISSUE TITLE
Available in Fedora 35/36

### ISSUE THREAD

**Issue by awvwgk** [jacobwilliams/json-fortran#519]
Looks like `json-fortran` is now packaged for Fedora, see https://bugzilla.redhat.com/show_bug.cgi?id=2089880.

**Comment by jacobwilliams** [comment]
Interesting. I should add this to the readme. 

I think maybe it's also in other package managers too:

* https://packages.simplyfortran.com
* others?

**Comment by awvwgk** [comment]
Repology lists most repositories which provide a suitable index: https://repology.org/project/json-fortran/versions

Also provides a badge version to keep track of the repositories a package is available in

[![Packaging status](https://repology.org/badge/vertical-allrepos/json-fortran.svg)](https://repology.org/project/json-fortran/versions)
