### ISSUE TITLE
Cross-platform?

### ISSUE THREAD

**Issue by lolaswift** [jacobwilliams/json-fortran#520]
How to make it work for Windows?

**Comment by lolaswift** [comment]
I now have the  jsonfortran.lib generated by using the visual studio project which was generated by CMake. How can I use it with commandline ifort or in vistual studio. I've tried many ways including adding dependencies to the project. Didn't work.

**Comment by jacobwilliams** [comment]
What have you tried? To use a library in an existing project is a general programming question (e.g., check your compiler and/or IDE documentation).
