### ISSUE TITLE
build.sh failing with ifort

### ISSUE THREAD

**Issue by zbeekman** [jacobwilliams/json-fortran#53]
On OS X Yosemite, with
```shell
$ ifort -v
ifort version 15.0.2
```

if I set [`use_ifort=1`](https://github.com/jacobwilliams/json-fortran/blob/master/build.sh#L14) in [`build.sh`](https://github.com/jacobwilliams/json-fortran/blob/master/build.sh#L14) the build fails with this output: https://gist.github.com/zbeekman/d89663e5c9669217ed0c

I’m not sure if this is an issue with @szaghi’s [FoBiS.py](../../../../szaghi/FoBiS) or an issue with @jacobwilliams’ [`build.sh`](../blob/master/build.sh)

**Comment by szaghi** [comment]
I am not sure, but it seems an issue of fobis: it seems that building the
library fobis searches for a main program... strange. Unfortunately i
cannot fix it until monday when i come back to office.
Il 20/feb/2015 23:25 "Izaak Beekman" <notifications@github.com> ha scritto:

**Comment by szaghi** [comment]
Wait... at line 50 of build script the cflags are enclosed into a couple of
"... there is a known bug  into argparse (the python module that fobis uses
for its cli) that imposes to insert a white space after the first " so your
fobis invocation should be somenthing like

FoBiS.py build ... cflags " $(....)"...

I am not completely sure, but i think should be some docs into fobis wiki.
Il 21/feb/2015 09:12 "Stefano Zaghi" <stefano.zaghi@gmail.com> ha scritto:

**Comment by zbeekman** [comment]
@jacobwilliams incoming PR fixing this issue. @szaghi there was an errant space in the intel flags. I’m not sure why this causes the build with FoBiS.py to fail.
