### ISSUE TITLE
Issue While attempting to Configure build directory using Cmake

### ISSUE THREAD

**Issue by Madhav-byte-debug** [jacobwilliams/json-fortran#552]
I cloned the repo locally to a desktop folder. created a directory "b" within the repo folder.
After running `cmake C:\Users\Admin\Desktop\HPC\json-fortran` I get the following error.

```
CMake Error at CMakeLists.txt:25 (enable_language):
  Running

   'nmake' '-?'

  failed with:

   no such file or directory


CMake Error: CMAKE_Fortran_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
```

**Comment by borderite** [comment]
Did you put your compiler name (e.g., /usr/bin/gfortran)  in the environment variable "FC"?

**Comment by jacobwilliams** [comment]
Yes you need to CMake what compiler to use. You can consult the CMake documentation about how to specify the compiler.
