### ISSUE TITLE
Alternative to using array constructor for writing array to JSON?

### ISSUE THREAD

**Issue by kmanalo** [jacobwilliams/json-fortran#58]
Hi all,

I was just wondering if there was an alternative way of being able to write an array, as I am working with a derived-type variable string array; I'm having a hard time writing using the array constructor directly, without writing to a fixed-length char array. 

Here is my distilled version of the kind of thing I'm currently doing, which works with gfortran 4.9.2:

```Fortran
    ! the kind of data structure I'm working with
    type string
      character(len=:), allocatable :: str
    end type string
    type(string),  dimension(:), allocatable :: derived_type_array

    ! put data in derived_type_array
    ...
    
    character(len=20), allocatable :: strarr(:)
    ! workaround to get string array output to JSON , I picked 20 as it was suitable for my needs
    allocate(strarr(size(derived_type_array)))
    do i=1,size(derived_type_array)
      strarr(i) = derived_type_array(i)%str
    end do
    call json_add(outp, 'char_array', [(strarr(i),i=1,size(derived_type_array))] )

    ! more stuff related to closing the JSON pointer / file
    ...
```
When I don't performed the `strarr` assignment via fixed-length char arrays, I get empty strings in the JSON output array.

How can I avoid doing this?  My only thought was maybe having a method to perform scalar writes to an array, to avoid the above workaround.  I also have not tried another Fortran compiler (yet). It's been such a long time for me to work with character arrays, so maybe I'm just trying too hard, and there is an alternative array add example?  If there is more interest, I could improve this up to minimal working example.  At the very least maybe I can contribute a unit test.

Again, I'm very appreciative of the source code! This has really envigorated my re-learning of the latest standard, and made Fortran so much easier to interface with regards to file I/O ease.

**Comment by jacobwilliams** [comment]
Yes, there is a way to do it.  Stand by for example...

**Comment by kmanalo** [comment]
@jacobwilliams thanks, looking forward to it!

**Comment by jacobwilliams** [comment]
OK, this might be what you need.  The idea is you have to create an empty array object, and then add the strings one at a time.  Then you add this array to your main json structure.  There is no need to put the allocatable string into a temp string.  Code snippet below.  

```Fortran
type(json_value),pointer :: array  !temp for creating the array

call json_create_array(array, 'char_array')  !create an empty array

!add each element (note: name is not used)
do i=1,size(derived_type_array)
  call json_add(array, '', derived_type_array(i)%str)  ![this is json_value_add_string]
end do

call json_add(outp, array)  !add the array to the output [this is json_value_add_member]
nullify(array) !don't need this anymore
```
**Note**: I haven't tried to compile a working example, so if you can't get it to work, let me know.  I think this should work.  Also: be aware that Gfortran still has some bugs related to the allocatable character strings... I've got several workarounds in json-fortran to account for them, but it's possible you could be seeing one of them in your code..not sure.

**Comment by kmanalo** [comment]
@jacobwilliams I will give this approach a shot and let you know how it goes.

**Comment by zbeekman** [comment]
I wonder if it would be worth the hassle to add some kind of direct ragged edge string array API… I can’t quite picture what it would look like at the moment, without publicizing a new ragged edge string array derived type, which is likely beyond the scope of this project.

**Comment by jacobwilliams** [comment]
I think it would have to look like @kmanalo's ```string``` type above.  Then we would have ```json_get```, etc. routines for this type. I actually thought about something like this before, but decided against it. Perhaps one day, Fortran will let us have arrays of allocatable strings...

**Comment by zbeekman** [comment]
yeah exactly what I was thinking… probably best to leave it alone for now. 

btw, auto-deploy almost done :-)

**Comment by kmanalo** [comment]
I tried your suggestion and it worked out very well.

Thanks, this was helpful in a non-string context also, in working with double precision arrays.  I had a similar need to avoid the array constructor there also.

Also, I'm a dummy, this may be more of a semantic issue: every time I read the comment "don't need this anymore" in the suffix to nullify(), I totally thought that meant that one didn't need to use nullify anymore.  I get it now.

**Comment by jacobwilliams** [comment]
Ha ha! Yeah, I was just saying that the pointer is no longer needed once the data it is pointing to has been added to the ```outp``` structure. I nullify it just to be safe (for example, you might want to reuse it later on).  Note that the ```json_destroy``` routine deallocates the memory and destroys the linked list, which is not appropriate here for ```array``` (since the data itself is now part of ```outp```), but would be appropriate to call for ```outp```, when you are finished with it, in order to avoid a memory leak.
 
Happy to help!

**Comment by zbeekman** [comment]
Speaking of memory leaks, I wonder what it would take to get a reference counting scheme going, for better automatic memory management… it seems that there is a rather large burden on the end user to ensure that they cleanup after themselves to avoid memory leaks, but at the same time ensure that they don’t create any dangling pointers.

**Comment by jacobwilliams** [comment]
For the ```json_file``` class it might be fairly easy I think (we could even try to use a ```final``` method...although last time I tried that it was buggy).  However, if you are using ```json_value``` pointers to build your own structure, I'm not sure how that would work...it could be tricky.  It may be possible...but I've not thought in detail how that would work with Fortran pointers.
