### ISSUE TITLE
Wiki documentation

### ISSUE THREAD

**Issue by jacobwilliams** [jacobwilliams/json-fortran#66]
Consider moving some of the how-to information from the README.md file to the Wiki and expanding.  For example, to cover a lot of different sorts of use cases, explain subtle details, avoiding memory leaks, etc.

**Comment by zbeekman** [comment]
I just [added a page](https://github.com/jacobwilliams/json-fortran/wiki/List-of-un-exercised-code) to enumerate the heretofore untested library procedures, using the coverage information collected from the unit tests and [posted to coveralls](https://coveralls.io/builds/2034976/source?filename=src%2Fjson_module.f90).

**Comment by zbeekman** [comment]
Added [another page](https://github.com/jacobwilliams/json-fortran/wiki/Unicode-How-To) with some usage information for Unicode

**Comment by zbeekman** [comment]
I’m trying to update the coverage wiki page, and can’t seem to generate the function report any more… I am probably doing something wrong, and am looking through our various discussions to try to figure out how to update this.

**Comment by jacobwilliams** [comment]
Do you have instructions somewhere on how to generate the coverage wiki page? I don't think I've ever tried to do it.

**Comment by zbeekman** [comment]
I figured it out, I had an old/bad gcov file. I'll update later and add
instructions
