### ISSUE TITLE
CMake produced Visual Studio Project

### ISSUE THREAD

**Issue by jacobwilliams** [jacobwilliams/json-fortran#70]
Figure out if we can use CMake to automatically generate a Visual Studio project. If so, provide some instructions on how to do it, and remove the VS project currently there.

**Comment by jacobwilliams** [comment]
Tried this unsuccessfully on Windows using cMake-gui. For one thing, Ford is crashing in the "Configure" stage (could be [this bug](https://github.com/cmacmackin/ford/issues/146)). When I disable Ford, I can generate the project, but it doesn't compile. It looks like the include file is not being seen. Will tinker with it some more later.

**Comment by jacobwilliams** [comment]
It looks like there are a couple forks where people are doing something with CMake and Visual Studio (see https://github.com/handrake0724/json-fortran/commit/101f193cdf06440af25d8ea807a09f85b57eafe2 and https://github.com/BlueQuartzSoftware/json-fortran/commit/ef2ee157c3bfca5cde4564269f35dc616c5cfe85 ). @imikejackson and @handrake0724 do you have any interest in committing your change back into the main project?

**Comment by handrake0724** [comment]
Hi, Jacob

it would be my pleasure to contribute your code. I think BlueQuartzSoftware's work is made better than mine.

Regards

**Comment by jacobwilliams** [comment]
Note: I committed the changes (with @handrake0724 version as a guide) so that it will successfully generate a usable Visual Studio project on Windows.
