### ISSUE TITLE
get and get … vec discrepancy with dummy argument attributes for path

### ISSUE THREAD

**Issue by zbeekman** [jacobwilliams/json-fortran#79]
I noticed that a number of subroutines, like `json_get_integer` and `json_get_integer_vec` have a discrepancy when it comes to the `path` argument. For the scalar version, `path` is an optional argument, whereas for the vector version `path` is a mandatory argument…

This may not be a bug at all, but I was wondering if you could help me understand the discrepancy.. Looking at `json_get_array` it looks like the get_…_vec routines should have the `path` as an `optional` argument…

**Comment by zbeekman** [comment]
FWIW, the optional attribute to `path` really complicates overloading these procedures to enable path to be specified as ASCII rather than UCS4. So from a complexity viewpoint, making path mandatory would be nice… but there’s another work around too, if we want to keep path optional… just need write more wrappers.

**Comment by jacobwilliams** [comment]
I think it's an oversight...I can't think of why I would do that on purpose. Like the scalar ones, it should be optional and assume ```me``` if not present...otherwise I think you'd have to use ```@``` as the path, which is somewhat obscure.

**Comment by zbeekman** [comment]
One more question, if I have to split the interface. (I would do this because the kind of optional arguments can't be used to resolve overloaded procedures.)

> otherwise I think you'd have to use `@` as the path

Does this mean that if `me` _**and**_ `path` are passed, but `path` is `@` it has the same effect as not passing the `path` argument? If so that will give me a work around for the disambiguation issue. (i.e. a way to make it behave as if there is an optional argument path, but without using the optional attribute.)

**Comment by jacobwilliams** [comment]
Yes, these two are equivalent: 
```Fortran 
call json_get_integer(me, path='@', value=value)
``` 
and 
```Fortran
call json_get_integer(me, value=value)
```
The 2nd one is more efficient, since the path does not have to be parsed.

**Comment by zbeekman** [comment]
If I do end up needing to make a wrapper, I’ll short circuit the path parsing logic if `path=‘@‘` if you’re worried about it slowing things down.
