### ISSUE TITLE
logic of top level if construct in json_get_double

### ISSUE THREAD

**Issue by zbeekman** [jacobwilliams/json-fortran#80]
`json_get_double`, `json_get_integer` and the like all start by immediately branching into an if statement:

```fortran
if (.not. exception_thrown) then
    ! Do the work
else
    value = 0.0_RK
    if (present(found)) found = .false.
end if
end subroutine
```

I traced this through the git history, using the ‘blame’ functionality on github, and this dates back to the initial commit.

To me, the logic of this is unnecessary, and possibly wrong. Under what circumstances would we anticipate `exception_thrown` to be true upon entry, and want to set the value to 0.0 and return?

The only suspect I can think of is the array callback stuff, but I can’t seem to figure out why we would want this in this case either…

**Comment by jacobwilliams** [comment]
The idea is that when an exception is thrown, the routine does nothing.  In this case, i just set the outputs to something (to avoid any problems in case the outputs are being checked by whatever is calling this routine).  The exception has to be handled by the caller.

**Comment by zbeekman** [comment]
ah, I see… OK, I guess that does make sense… let the caller handle the exceptions…
