### ISSUE TITLE
0 bad choice for unit number when string is to be used instead of file

### ISSUE THREAD

**Issue by zbeekman** [jacobwilliams/json-fortran#85]
This is bad because for many compilers, 0 is `error_unit` AKA ‘stderr’

The safest thing to do would be to code around this completely and rather than detecting a certain unit number either make the unit number optional or add some kind of flag.

**Comment by zbeekman** [comment]
Negative unit numbers are disallowed, but I seem to recall a compiler bug wherein calls to the `open` intrinsic with the `newunit=` specifier would return negative unit numbers. So in my mind, changing from zero to less than zero is a potential solution but less than ideal.

**Comment by szaghi** [comment]
```fortran
USE, intrinsic:: ISO_FORTRAN_ENV, only: stdout=>OUTPUT_UNIT, stderr=>ERROR_UNIT, IOSTAT_END, IOSTAT_EOR 

...
function Get_Unit(Free_Unit) result(funit)
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Procedure for obtaining a free logic unit for safely opening a file.
  !<
  !< @note If no units are available, -1 is returned.
  !<
  !<### On-the-fly usage
  !< The unit value is returned by the function and also by the optional argument *Free_Unit*. This allows the function to
  !< be used directly (on-the-fly) in an open statement like
  !<```fortran
  !< open(unit=Get_Unit(myunit),...) ; read(myunit)...
  !<```
  !---------------------------------------------------------------------------------------------------------------------------------
  implicit none
  integer::                        funit     !< Free logic unit.
  integer, intent(OUT), optional:: Free_Unit !< Free logic unit.
  integer::                        n1        !< Counter.
  integer::                        ios       !< Inquiring flag.
  logical::                        lopen     !< Inquiring flag.
  !---------------------------------------------------------------------------------------------------------------------------------

  !---------------------------------------------------------------------------------------------------------------------------------
  funit = -1
  if (present(Free_Unit)) Free_Unit = funit
  n1=1
  do
    if ((n1/=stdout).AND.(n1/=stderr)) then
      inquire (unit=n1,opened=lopen,iostat=ios)
      if (ios==0) then
        if (.NOT.lopen) then
          funit = n1 ; if (present(Free_Unit)) Free_Unit = funit
          return
        endif
      endif
    endif
    n1=n1+1
  enddo
  return
  !---------------------------------------------------------------------------------------------------------------------------------
  endfunction Get_Unit
...
integer:: free_unit
...
open(unit=Get_Unit(free_unit),...)
...
write(free_unit...)..
```

**Comment by zbeekman** [comment]
@szaghi Thanks for the tip, but the issue here is *NOT* finding a new unit. (I actually have some very similar code to yours that that I use in some of my other projects....) This issue is that, currently, json-fortran uses `unit=0` to have a special meaning: operate on a string rather than an external file. The problem with this is that 'stderr' is often connected on 0. If you pass 'ERROR_UNIT' as the unit number to certain json-fortran API calls, this will result in an error, rather than what the user probably intended: printing the json structure to stderr/ERROR_UNIT.

**Comment by szaghi** [comment]
opsss, I am very sorry :-(  I read it too superficially!

**Comment by jacobwilliams** [comment]
Note: ```newunit``` will always return a negative number (it's not a bug when that happens).  User-specified unit numbers must be positive, but ```newunit``` values will always be negative (at least that's what "Modern Fortran Explained" says).

I think making it optional for the string case would probably be the way to go. It's unlikely that anyone would try to print a file to stderr, but it doesn't hurt to be safe.

**Comment by szaghi** [comment]
Hoping to amend my previous error... I confirm the @jacobwilliams comment. From the standard

```
9.5.6.12
 NEWUNIT= specifier in the OPEN statement
1 The variable is defined with a processor determined NEWUNIT value if no error occurs during the execution of
the OPEN statement. If an error occurs, the processor shall not change the value of the variable.
2 A NEWUNIT value is a negative number, and shall not be equal to -1, any of the named constants ERRORUNIT, INPUT UNIT, or OUTPUT UNIT from the intrinsic module ISO FORTRAN ENV (13.8.2), any value
used by the processor for the unit argument to a defined input/output procedure, nor any previous NEWUNIT
value that identifies a file that is currently connected.
-
```

**Comment by zbeekman** [comment]
ah OK, I see… 

As for it being “unlikely that anyone will want to print a file to stderr” I just discovered this issue by trying to do exactly that! :troll face:

**Comment by jacobwilliams** [comment]
Ha ha!  Fair enough!

**Comment by zbeekman** [comment]
btw json-fortran got listed on json.org

**Comment by jacobwilliams** [comment]
Awesome! I never tried to use the YAJL-Fort one...it looked too complicated for a poor Fortran man...

**Comment by zbeekman** [comment]
Also, reading the text from the standard that @szaghi posted, indicates that as a cheap/dirty hack we could also just switch 0 to -1… just a thought

**Comment by zbeekman** [comment]
Any opposition to switching from 0 to -1, @jacobwilliams? This will be an easy fix, and unless a certain compiler uses -1 for  stderr/stdin/stdout it seems safe to me, according to:

> 9.5.6.12
 NEWUNIT= specifier in the OPEN statement
1 The variable is defined with a processor determined NEWUNIT value if no error occurs during the execution of the OPEN statement. If an error occurs, the processor shall not change the value of the variable.
2 A NEWUNIT value is a negative number, and shall not be equal to -1, any of the named constants ERRORUNIT, INPUT UNIT, or OUTPUT UNIT from the intrinsic module ISO FORTRAN ENV (13.8.2), any value used by the processor for the unit argument to a defined input/output procedure, nor any previous NEWUNIT value that identifies a file that is currently connected.

I may try to hack at this soon, and get the test coverage up a little bit. The suggestions feature of codecov.io is nice and shows you how you can increase coverage with the most bang for your buck.

**Comment by jacobwilliams** [comment]
I'm ok with changing to -1.
