### ISSUE TITLE
PGI Compilation Issues with 15.1 (status update)

### ISSUE THREAD

**Issue by kmanalo** [jacobwilliams/json-fortran#87]
Hi all,

I just wanted to show that

http://www.pgroup.com/userforum/viewtopic.php?t=4636&highlight=internal+subprogram+passed+argument

```
PGF90-S-0439-An internal subprogram cannot be passed as argument - get_int_from_array (/Users/kmanalo/github/json-fortran/src/json_module.f90: 3434)
PGF90-S-0439-An internal subprogram cannot be passed as argument - get_int_from_array (/Users/kmanalo/github/json-fortran/src/json_module.f90: 3434)
  0 inform,   0 warnings,   2 severes, 0 fatal for json_get_integer_vec
PGF90-S-0439-An internal subprogram cannot be passed as argument - get_double_from_array (/Users/kmanalo/github/json-fortran/src/json_module.f90: 3569)
PGF90-S-0439-An internal subprogram cannot be passed as argument - get_double_from_array (/Users/kmanalo/github/json-fortran/src/json_module.f90: 3569)
  0 inform,   0 warnings,   2 severes, 0 fatal for json_get_double_vec
PGF90-S-0439-An internal subprogram cannot be passed as argument - get_logical_from_array (/Users/kmanalo/github/json-fortran/src/json_module.f90: 3698)
PGF90-S-0439-An internal subprogram cannot be passed as argument - get_logical_from_array (/Users/kmanalo/github/json-fortran/src/json_module.f90: 3698)
  0 inform,   0 warnings,   2 severes, 0 fatal for json_get_logical_vec
PGF90-S-0439-An internal subprogram cannot be passed as argument - get_chars_from_array (/Users/kmanalo/github/json-fortran/src/json_module.f90: 3964)
PGF90-S-0439-An internal subprogram cannot be passed as argument - get_chars_from_array (/Users/kmanalo/github/json-fortran/src/json_module.f90: 3964)
```

Just letting you know that PGI is slow to catch up to 2008 features.

15.3 had some fixes but not this particular one.

BTW, I haven't forgot about contributing the NAG flags (will do that when I can get to it).

**Comment by zbeekman** [comment]
well this is the only compatibility issue that they report… there may be others or bugs…

Sadly there is no obvious/easy work around for this because the array callback functions are setup for the express purpose of providing access to the local variables in the routine in which they are declared.

**Comment by zbeekman** [comment]
I would file this issue under “blocked by vendor issue” unless someone feels ambitious enough to code up a work around.

**Comment by kmanalo** [comment]
Might be best to wait on PG/nVidia to get this implemented ... I'll follow the trail for the 15.X series and see if anything comes up in their compiler updates.

**Comment by zbeekman** [comment]
btw,  @kmanalo did you manually set your GH avatar or is that the one that got automatically generated for you?

**Comment by kmanalo** [comment]
lol, no, it was generated for me, though I haven't seen many other happy face avatars.

**Comment by zbeekman** [comment]
@kmanalo Just wondering if there have been any recent PGI compiler updates.

**Comment by kmanalo** [comment]
They do have a 15.5 update, but I only see notes on 15.4 on their website.
Would be interested to see if they added in support for the array callback.

It's on my agenda to work with 15.5 (I've been working with 15.ODD series),
so I'll definitely give it a try this week and let you know if there are
any improvements.

**Comment by kmanalo** [comment]
PGF90-S-0439 issue still present on 15.5

**Comment by zbeekman** [comment]
@kmanalo unless you can think of an easy work around I suspect we’ll just leave this as is until PGI supports internal procedures passed as actual arguments…

Any updates on the NAG compilation and flags? Is it as simple as `export FC=$(which ftn)` (or whatever NAG calls their fortran compiler….) followed by `cmake build-dir` etc?

**Comment by kmanalo** [comment]
Thanks again for the reminder on the NAG flags.  I have the flags on a home
box, but I'll try to checkout the last version I had and at least copy
paste back here later.

There were some custom flags that I want to get from that commit.

**Comment by zbeekman** [comment]
@kmanalo any news on NAG?

**Comment by kmanalo** [comment]
I finally found a file with some of the backtrace options for NAG.  

In `pickFortranCompilerFlags.cmake `
```
  elseif ( "${CMAKE_Fortran_COMPILER_ID}" MATCHES "NAG" )
    if ( ENABLE_BACK_TRACE )
      set ( CMAKE_Fortran_FLAGS "${CMAKE_Fortran_FLAGS} -gline -C")
    endif ()
  endif ()
```

BTW, separate from NAG, reading through the release notes for PGI 15.7 it appears this issue #87 still "blocked by vendor issue"

**Comment by zbeekman** [comment]
Was that all that was required to get it working with NAG?

It's ridiculous that PGI hasn't implemented passed internal procedures yet.

**Comment by zbeekman** [comment]
@kmanalo Were those the only changes needed for NAG support?

**Comment by kmanalo** [comment]
Only for traceback options. I have not yet read/researched the compiler
options for the equivalent to: ENABLE_COMPILETIME_{WARNINGS,CHECKS} and
ENABLE_RUNTIME_CHECKS

I would like to compare and contrast that with Intel and GNU.

**Comment by kmanalo** [comment]
Before I forget, Tim Kaiser's page (Colorado School of Mines HPC) had a
good reference for the lazy: http://geco.mines.edu/guide/errortracking/
surveying traceback options for the 3 compilers.  It's dated from 2011, but
helped me get the traceback working.

**Comment by kmanalo** [comment]
http://fortranwiki.org/fortran/show/Debugging+tools
http://www.nag.com/nagware/np/r60_doc/np60_manual.pdf

I cross-checked with the nagfor documentation here: 
nagfor 
`-g -C=all -nan`

`-g` 
"interactive debugging"

`-C=all`
"Compile checking code according to the value of check, which must be one of:
all 	(perform all checks except for -C=undefined),"

`-nan`
"Initialise REAL and COMPLEX variables to IEEE Signalling NaN, causing a runtime crash if the values are used before being set. This affects local variables, module variables, and INTENT(OUT) dummy arguments only; it does not affect variables in COMMON or EQUIVALENCE."

Warnings appear to be on by default (the warning options are all about suppression)

**Comment by zbeekman** [comment]
@kmanalo Please let me know once you are satisfied with the list of NAG
flags (and what they are and what they do), then I'll add them to the CMake
build.

**Comment by zbeekman** [comment]
I have access to PGI 16.x and can give it a shot...

Also, PGI is free on OS X. It might be worth looking into getting it installed from a travis-ci os x image script and testing... also free intel compilers for linux mean that we might be able to build a docker machine to test ifort as well...

**Comment by mgovoni-devel** [comment]
Hi, is there any update on this? I noticed that there are several compilation errors with Pgfortran 19.4 (April 2019). Are there plans to make json-fortran compatible with Pgfortran? Thanks.

**Comment by jacobwilliams** [comment]
Are the errors still just Fortran 2008 features that PGI hasn't added yet? I've never used PGI before.

If it's something minor that we can work around I'm OK with making it compatible... but I don't want to restructure the code significantly just for this. They need to join us in the future (of 2008). :)
