### ISSUE TITLE
css broke on gh-pages index.html

### ISSUE THREAD

**Issue by zbeekman** [jacobwilliams/json-fortran#89]
see: http://jacobwilliams.github.io/json-fortran/

**Comment by jacobwilliams** [comment]
You mean the blue color scheme? I did that on purpose! I was experimenting with some different colors, since I don't really like the tan/brown/black default palette.

**Comment by szaghi** [comment]
tan/brown/black default palette is too poor also for Jacob :-)

**Comment by zbeekman** [comment]
oh, I see…. Interesting… well in that case, keep on experimenting and when you find something you like, we can update the style sheets for the ROBODoc generated output too…
