### ISSUE TITLE
Unicode + Gfortran 5.1

### ISSUE THREAD

**Issue by jacobwilliams** [jacobwilliams/json-fortran#94]
All the tests fail when Unicode is enabled when compiling with the latest gfortran 5.1 build (using the MacOS X binary from http://coudert.name).

**Comment by zbeekman** [comment]
Can you please elaborate some more on what is happening? I can’t seem to reproduce this on my system. I have even I cloned a fresh copy of your repo and it works with and without enabling UNICODE, compiling with `build.sh` and CMake… I am using gfortran 5.1 from the link you provided.

**Comment by jacobwilliams** [comment]
Well, maybe that's good news (bad news for me though...maybe there's something wrong with my system for some reason)  It seems like all the strings are getting garbled when passed into the subroutines...  I'll look into it some more later.

**Comment by zbeekman** [comment]
I’m an intel beta tester and just wanted to let you know, that the master branch (and presumably the most recent release) compiler and pass all tests with the latest Intel Beta. Still can’t reproduce the gfortran 5.1 problem with the unicode support. BTW, GREAT job on the speed improvements.

**Comment by zbeekman** [comment]
Let me know if you can track down what’s going on or how I can reproduce it… it would be nice to figure this out and close this ticket

**Comment by jacobwilliams** [comment]
Reinstalled gfortran, and the issue is no longer happening. (Also updated Xcode, so maybe that also had something to do with it).  Weird, but I'll take it.

**Comment by zbeekman** [comment]
:relieved: phew!
