### ISSUE TITLE
Homebrew install and thoughts about restructuring install directories a little bit

### ISSUE THREAD

**Issue by zbeekman** [jacobwilliams/json-fortran#98]
I have a [homebrew formula](http://git.io/vTE4h) which will build and “install” json-fortran, but due to the non-canonical install directory structure we currently have 
```
/usr/local/jsonfortran-gnu-4.0.0/
├── cmake
│   ├── jsonfortran-gnu-config-version.cmake
│   ├── jsonfortran-gnu-config.cmake
│   ├── jsonfortran-gnu-targets-release.cmake
│   └── jsonfortran-gnu-targets.cmake
└── lib
    ├── json_module.mod
    ├── libjsonfortran.4.0.0.dylib
    ├── libjsonfortran.4.0.dylib -> libjsonfortran.4.0.0.dylib
    ├── libjsonfortran.a
    └── libjsonfortran.dylib -> libjsonfortran.4.0.dylib
```
Home-brew doesn’t link anything in to `/usr/local/lib` or `/usr/local/include`, which seems to be the place that other home-brewed fortran projects put their .mod files. We discussed some of the installation considerations in #3.

I’m inclined to add a CMake option to  use the canonical install locations IFF gfortran is being used to compile the library. The user can then set this option and the library files will be installed into /usr/local/lib by default and the .mod file will get placed in /usr/local/include (and when managed with homebrew they will be symlinked in). As for the  cmake files telling cmake where to find everything the convention appears to be either copy them into /usr/local/lib/cmake (which is what scalapack does) or to copy them into /usr/local/lib/<project-name>/ which is what cloog-isl does.

Thus, the proposed install structure would look like:
```
/usr/local/
├── include
│   └── json_module.mod
└── lib
    ├── cmake
    │   └── json-fortran-4.0.0
    │       ├── jsonfortran-gnu-config-version.cmake
    │       ├── jsonfortran-gnu-config.cmake
    │       ├── jsonfortran-gnu-targets-release.cmake
    │       └── jsonfortran-gnu-targets.cmake
    ├── libjsonfortran.4.0.0.dylib
    ├── libjsonfortran.4.0.dylib
    ├── libjsonfortran.a
    └── libjsonfortran.dylib
```
and this would be achieved by passing a switch to `cmake` or editing an option in the cache with `ccmake` or `cmake-gui` to tell it to install in the canonical way rather than the current way, which installs it to /usr/local/jsonfortran-gnu-x.x.x/ as described above.

This way users could fetch and install json-fortran directly using homebrew and the `brew link` step would actually link the libraries and mod files etc. to reasonable locations. Thoughts?

**Comment by zbeekman** [comment]
If you, @jacobwilliams are amenable to this idea I’ll try to work up a PR

**Comment by jacobwilliams** [comment]
Sounds fine to me!

**Comment by zbeekman** [comment]
I’m nearly ready to submit a PR to Homebrew/homebrew, but I was hoping you could create a new release (4.1.1 or 4.2.0 … I need to look at semver.org again to figure out if the changes are sufficient for a patch bump vs minor bump) so that there is a release with the update to the CMake build system from PR #101 . Also if you decide to merge PR #102 please do so first, before making a new tag & release.

**Comment by jacobwilliams** [comment]
Done. I went with 4.1.1.

**Comment by zbeekman** [comment]
Thank you much! Will update my Homebrew formula and then submit a PR to Homebrew/homebrew… if they don’t take it, hopefully then the homebrew/science tap will take it.

**Comment by jacobwilliams** [comment]
Awesome!

**Comment by zbeekman** [comment]
PR submitted, had to fix some stuff: https://github.com/Homebrew/homebrew/pull/40128

**Comment by zbeekman** [comment]
https://github.com/Homebrew/homebrew/pull/40128 accepted! Will try to update the README via PR tomorrow
