### ISSUE TITLE
possible travis-ci breakage

### ISSUE THREAD

**Issue by zbeekman** [jacobwilliams/json-fortran#99]
I’m not sure why but my fork of the master brach of json-fortran is erroring. It appears something about the travis-ci environment may have changed. The first error is caused by trying to install nodejs. The second error is due to gfortran-4.9 not being able to be installed anymore…. This may just be a transient travis-ci issue, but it’s worth keeping an eye on

**Comment by zbeekman** [comment]
@jacobwilliams can you try resubmitting the last travis job? I think it’s broken and that I have a fix, but I don’t understand why it’s broken.

**Comment by jacobwilliams** [comment]
[Done](https://travis-ci.org/jacobwilliams/json-fortran/builds/62155139)

**Comment by zbeekman** [comment]
that’s so odd…. well at any rate I have a fix… PR incoming soonish
